import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
mkdirSync('.test-build',{recursive:true});for(const name of ['api','security','engine','provider','storage','types','preferences','proof']){const source=readFileSync('lib/ledger/'+name+'.ts','utf8');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.js'");writeFileSync('.test-build/'+name+'.js',compiled);}
const {handle}=await import('../.test-build/api.js');const security=await import('../.test-build/security.js');const engine=await import('../.test-build/engine.js');const {callModel,geminiModels,providerKey,reviewAI}=await import('../.test-build/provider.js');
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('drizzle/0000_slimy_cammi.sql','utf8'));
class Statement{constructor(q){this.q=q;this.args=[];}bind(...a){this.args=a;return this;}async first(){return sqlite.prepare(this.q).get(...this.args)||null;}async all(){return {results:sqlite.prepare(this.q).all(...this.args)};}async run(){const r=sqlite.prepare(this.q).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
const blobs=new Map();const env={DB:{prepare:q=>new Statement(q),batch:async statements=>{sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}},BUCKET:{put:async(k,v)=>{blobs.set(k,typeof v==='string'?new TextEncoder().encode(v):v);},get:async k=>blobs.has(k)?{body:blobs.get(k),arrayBuffer:async()=>blobs.get(k).buffer}:null},LQ_ENCRYPTION_KEY:'test-only-secret-'.repeat(5)};
let cookie='',otherCookie='',otherCsrf='',csrf='',wid='',revision=1;const receipts=[];
async function test(name,fn){await fn();receipts.push({name,result:'PASS'});console.log('PASS '+name);}
async function request(path,body,auth=true){const headers={};if(body){headers['Content-Type']='application/json';headers.origin='https://ledger.test';if(auth)headers['x-lq-csrf']=csrf;}if(auth)headers.cookie=cookie;const res=await handle(env,new Request('https://ledger.test/api/ledger/'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined}),path.split('/'));let data;try{data=await res.clone().json();}catch{data=await res.text();}return {res,data};}
async function refresh(){const r=await request('state?workspaceId='+wid); // handle receives path including query below via wrapper
 return r;}
async function state(){const r=await handle(env,new Request('https://ledger.test/api/ledger/state?workspaceId='+wid,{headers:{cookie}}),['state']);const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));revision=data.revision;return data;}
async function action(action,body={},key=crypto.randomUUID()){return request('action',{action,workspaceId:wid,expectedRevision:revision,operationKey:key,...body});}
await test('Ten-step proof reads saved public evidence and leaves private work untouched',async()=>{const r=await request('proof-checklist',null,false);assert.equal(r.res.status,200);assert.equal(r.data.workspaceId,'LQ-PUBLIC');assert.equal(r.data.steps.length,10);assert(r.data.originals.every(o=>o.verified));assert.equal(r.data.steps[8].status,'NOT ESTABLISHED');assert.equal(r.data.realUserBenefitsEstablished,false);assert.equal(r.data.steps[9].status,'PARTIAL');const saved=await request('demo',null,false);assert.equal(saved.data.state.records.find(r=>r.id==='EVT-OOS-026').status,'HOLD');});
await test('Missing public original is a visible checklist gap, never a success',async()=>{const demo=await request('demo',null,false);const key=demo.data.state.records.find(r=>r.id==='SRC-LAB-026').fields.objectKey;const original=blobs.get(key);blobs.delete(key);try{const r=await request('proof-checklist',null,false);assert.equal(r.data.steps[1].status,'PARTIAL');assert.equal(r.data.originals.find(o=>o.id==='SRC-LAB-026').verified,false);}finally{blobs.set(key,original);}});
await test('Saved read-only public case bootstraps and retains source hashes',async()=>{const a=await request('demo',null,false),b=await request('demo',null,false);assert.equal(a.res.status,200);assert.equal(a.data.state.records[2].id,b.data.state.records[2].id);assert.equal(a.data.state.records.find(r=>r.id==='EVT-OOS-026').status,'HOLD');assert.equal(a.data.state.records[0].hash,await security.hash(a.data.state.records[0].fields.text));});
await test('Public visitor cannot mutate workspace',async()=>{const r=await request('action',{action:'event'},false);assert.equal(r.res.status,401);});
await test('App account creation stores separate synthetic workspace',async()=>{const r=await request('signup',{name:'Synthetic Tester',email:'fixture@example.invalid',password:'synthetic-only-password-123',syntheticConsent:true},false);assert.equal(r.res.status,200,JSON.stringify(r.data));cookie=r.res.headers.get('set-cookie').split(';')[0];csrf=r.data.csrf;const session=await request('session');wid=session.data.workspaces[0].id;assert.notEqual(wid,'LQ-PUBLIC');assert.equal(session.data.user.emailVerified,false);});
await test('Private workspace state readback and owner role boundaries',async()=>{const s=await state();assert(s.roles.includes('Owner'));assert(!s.roles.includes('QA Reviewer'));assert.equal(s.state.records.length,0);assert.equal(s.state.jobs.length,0);assert.equal(s.state.policy.providerConsent,false);});
await test('Cross-origin save is rejected',async()=>{const res=await handle(env,new Request('https://ledger.test/api/ledger/action',{method:'POST',headers:{origin:'https://evil.test',cookie,'x-lq-csrf':csrf},body:'{}'}),['action']);assert.equal(res.status,400);});
await test('Missing CSRF cannot mutate data',async()=>{const res=await handle(env,new Request('https://ledger.test/api/ledger/action',{method:'POST',headers:{origin:'https://ledger.test',cookie},body:'{}'}),['action']);assert.equal(res.status,400);});
await test('Source permission is enforced before saving',async()=>{const before=revision;const r=await action('source',{title:'Denied',text:'must preserve',purpose:'test'});assert.equal(r.res.status,400);await state();assert.equal(revision,before);});

await test('Fresh workspace creation is explicit, private, empty and idempotent',async()=>{const body={name:'Separate fresh workspace',requestId:crypto.randomUUID()};const r=await request('workspaces/create',body);assert.equal(r.res.status,200,JSON.stringify(r.data));const again=await request('workspaces/create',body);assert.equal(again.data.workspaceId,r.data.workspaceId);assert(again.data.replayed);const res=await handle(env,new Request('https://ledger.test/api/ledger/state?workspaceId='+r.data.workspaceId,{headers:{cookie}}),['state']);const data=await res.json();assert.equal(data.state.records.length,0);const recent=await request('session');assert.equal(recent.data.workspaces.length,2);assert(recent.data.workspaces.every(w=>w.recordCount===0));});
await test('Working proof cannot overwrite populated private evidence',async()=>{const created=await request('workspaces/create',{name:'Preserve custom evidence',requestId:crypto.randomUUID()});const row=sqlite.prepare('SELECT state FROM workspaces WHERE id=?').get(created.data.workspaceId);const st=JSON.parse(row.state);st.records.push(engine.scenario().records[0]);sqlite.prepare('UPDATE workspaces SET state=? WHERE id=?').run(JSON.stringify(st),created.data.workspaceId);const r=await request('action',{action:'load-proof',workspaceId:created.data.workspaceId,expectedRevision:1,operationKey:crypto.randomUUID(),proofId:'DRUG-Q-OOS',confirmSynthetic:true});assert.equal(r.res.status,400);assert.match(r.data.error,/fresh empty/);assert.equal(JSON.parse(sqlite.prepare('SELECT state FROM workspaces WHERE id=?').get(created.data.workspaceId).state).records.length,1);});
await test('Original proof requires selection and consent before loading',async()=>{const r=await action('load-proof',{proofId:'DRUG-Q-OOS',confirmSynthetic:false});assert.equal(r.res.status,400);assert.equal((await state()).state.records.length,0);});
await test('Selected working proof saves separately and import replay never duplicates',async()=>{const key=crypto.randomUUID();const r=await action('load-proof',{proofId:'DRUG-Q-OOS',confirmSynthetic:true},key);assert.equal(r.res.status,200,JSON.stringify(r.data));const loaded=await state();assert.equal(loaded.state.workspace.proofTemplate,'DRUG-Q-OOS');assert.equal(loaded.state.records.find(x=>x.id==='EVT-OOS-026').status,'HOLD');assert(loaded.state.records.filter(x=>x.kind==='controlled_sources').every(x=>x.fields.objectKey.startsWith(wid+'/')));const again=await action('load-proof',{proofId:'DRUG-Q-OOS',confirmSynthetic:true},key);assert(again.data.replayed);assert.equal((await state()).state.records.length,loaded.state.records.length);const original=await request('demo',null,false);assert.equal(original.data.state.workspace.id,'LQ-PUBLIC');assert.equal(original.data.state.records.length,engine.scenario().records.length);const denied=await action('load-proof',{proofId:'DRUG-Q-OOS',confirmSynthetic:true});assert.equal(denied.res.status,400);});


await test('Default dashboard entry reuses only an empty private workspace and preserves selected proof',async()=>{const old=JSON.stringify((await state()).state);const r=await request('workspaces/create',{defaultEntry:true,name:'Fresh entry',requestId:crypto.randomUUID()});assert.equal(r.res.status,200,JSON.stringify(r.data));assert.equal(r.data.reusedEmpty,true);assert.notEqual(r.data.workspaceId,wid);const saved=JSON.parse(sqlite.prepare('SELECT state FROM workspaces WHERE id=?').get(r.data.workspaceId).state);assert.equal(saved.records.length,0);assert.equal(saved.workspace.proofTemplate,undefined);assert.equal(JSON.stringify((await state()).state),old);});
await test('Default dashboard entry creates empty work when all owned workspaces contain evidence, without clearing them',async()=>{const previous={cookie,csrf};try{const signup=await request('signup',{name:'Entry Tester',email:'entry@example.invalid',password:'synthetic-entry-password-123',syntheticConsent:true},false);cookie=signup.res.headers.get('set-cookie').split(';')[0];csrf=signup.data.csrf;const auth=await request('session');const old=auth.data.workspaces[0].id;const populated=engine.scenario(old);const serialized=JSON.stringify(populated);sqlite.prepare('UPDATE workspaces SET state=? WHERE id=?').run(serialized,old);const r=await request('workspaces/create',{defaultEntry:true,name:'Fresh dashboard',requestId:crypto.randomUUID()});assert.equal(r.res.status,200);assert.notEqual(r.data.workspaceId,old);assert.equal(JSON.parse(sqlite.prepare('SELECT state FROM workspaces WHERE id=?').get(r.data.workspaceId).state).records.length,0);assert.equal(sqlite.prepare('SELECT state FROM workspaces WHERE id=?').get(old).state,serialized);const repeat=await request('workspaces/create',{defaultEntry:true,requestId:crypto.randomUUID()});assert.equal(repeat.data.workspaceId,r.data.workspaceId);}finally{cookie=previous.cookie;csrf=previous.csrf;}});
await test('Fresh dashboard entry cannot bypass account authentication or CSRF',async()=>{const body={defaultEntry:true,requestId:crypto.randomUUID()};const anonymous=await request('workspaces/create',body,false);assert.equal(anonymous.res.status,401);const res=await handle(env,new Request('https://ledger.test/api/ledger/workspaces/create',{method:'POST',headers:{origin:'https://ledger.test',cookie},body:JSON.stringify(body)}),['workspaces','create']);assert.equal(res.status,400);});
await test('Personalization accepts display choices only, rejects corrupt stored values and never grants authority',async()=>{const {readPreferences,defaultPreferences}=await import('../.test-build/preferences.js');assert.deepEqual(readPreferences({density:'compact',accent:'cyan',text:'large',motion:'reduced',role:'QA Reviewer',approval:true}),{density:'compact',accent:'cyan',text:'large',motion:'reduced'});assert.deepEqual(readPreferences({density:'bad',accent:'url(secret)',text:'huge',motion:'always'}),defaultPreferences);assert.deepEqual(readPreferences(null),defaultPreferences);});

let sourceId;
await test('Authorized original saved to R2 with exact readback',async()=>{const r=await action('source',{title:'Synthetic completion evidence',text:'The operator must retain the original value.\nSynthetic training completion evidence.',purpose:'Control fixture',permission:true});assert.equal(r.res.status,200,JSON.stringify(r.data));sourceId=r.data.recordId;const s=await state();const record=s.state.records.find(r=>r.id===sourceId);assert.equal(record.hash,await security.hash(record.fields.text));const res=await handle(env,new Request('https://ledger.test/api/ledger/original?workspaceId='+wid+'&id='+sourceId,{headers:{cookie}}),['original']);assert.equal(await res.text(),record.fields.text);});
await test('Idempotent source operation does not duplicate original records',async()=>{const key=crypto.randomUUID();const r=await action('source',{title:'Replay test',text:'Evidence must be retained.',permission:true,purpose:'Test'},key);assert.equal(r.res.status,200);const count=(await state()).state.records.length;const again=await request('action',{action:'source',workspaceId:wid,expectedRevision:1,operationKey:key});assert.equal(again.res.status,200);assert(again.data.replayed);assert.equal((await state()).state.records.length,count);});
await test('Exact requirement extraction cites source/version/span',async()=>{const r=await action('extract',{id:sourceId});assert.equal(r.res.status,200);const s=await state();const req=s.state.records.find(r=>r.kind==='requirements'&&r.sourceIds.includes(sourceId));assert.equal(req.fields.sourceVersion,1);assert.equal(req.fields.statement,req.fields.span);});
await test('Stale expected workspace revision cannot save',async()=>{const r=await request('action',{action:'extract',id:sourceId,workspaceId:wid,expectedRevision:1,operationKey:crypto.randomUUID()});assert.equal(r.res.status,409);});
await test('Unconfigured live AI cannot fake success or transmit data',async()=>{const r=await action('agent',{id:'EVT-OOS-026',mode:'live'});assert.equal(r.res.status,400);assert.match(r.data.error,/consent|model/i);});
await test('Bounded deterministic team saves planning, specialists and human wait',async()=>{const r=await action('agent',{id:'EVT-OOS-026',mode:'deterministic'});assert.equal(r.res.status,200,JSON.stringify(r.data));assert.equal(r.data.status,'HOLD');const s=await state();const job=s.state.jobs.at(-1);assert.equal(job.phase,4);assert(job.outputs.length>=4);assert.equal(job.mode,'Deterministic');assert(s.state.records.some(r=>r.kind==='ai_runs'));});
await test('Executed control pack retains expected/actual cases and scope',async()=>{const r=await action('evaluate',{id:'AI-QA-01'});assert.equal(r.res.status,200);const s=await state();const run=s.state.records.filter(r=>r.kind==='evaluation_runs').at(-1);assert.equal(run.fields.denominator,12);assert(run.fields.cases.every(c=>c.pass));assert.match(run.fields.scope,/not model quality/);});
await test('Owner does not imply reviewer authority',async()=>{const s=await state();const target=s.state.records.find(r=>r.id==='CAPA-026');const r=await action('decision',{id:target.id,recordVersion:target.version,recordHash:await security.hash(JSON.stringify(target)),decision:'APPROVED',signingReason:'Approved',reason:'Fixture'});assert.equal(r.res.status,403);});
await test('Explicit synthetic reviewer role assignment succeeds',async()=>{const r=await action('member',{email:'fixture@example.invalid',roles:['Owner','Investigator','QA Reviewer','AI Reviewer'],syntheticAcknowledgement:true});assert.equal(r.res.status,200,JSON.stringify(r.data));const s=await state();assert(s.roles.includes('QA Reviewer'));});
let secret;
await test('Real TOTP enrollment requires the current authenticator code',async()=>{const start=await request('totp/start',{});assert.equal(start.res.status,200);secret=start.data.secret;const wrong=await request('totp/confirm',{otp:'000000'});assert.equal(wrong.res.status,400);const r=await request('totp/confirm',{otp:await security.otp(secret)});assert.equal(r.res.status,200);});
await test('Missing CAPA effectiveness blocks signed approval',async()=>{const s=await state();const target=s.state.records.find(r=>r.id==='CAPA-026');const r=await action('decision',{id:target.id,recordVersion:target.version,recordHash:await security.hash(JSON.stringify(target)),decision:'APPROVED',signingReason:'Approved',reason:'Fixture',password:'synthetic-only-password-123',otp:await security.otp(secret,Math.floor(Date.now()/30000)+1)});assert.equal(r.res.status,400);assert.match(r.data.error,/gap|effectiveness/i);});
await test('Named exact-revision request-evidence decision uses password and fresh OTP',async()=>{const s=await state();const target=s.state.records.find(r=>r.id==='CAPA-026');const r=await action('decision',{id:target.id,recordVersion:target.version,recordHash:await security.hash(JSON.stringify(target)),decision:'REQUEST_EVIDENCE',signingReason:'Reviewed',reason:'Synthetic reviewer requests missing effectiveness proof.',password:'synthetic-only-password-123',otp:await security.otp(secret,Math.floor(Date.now()/30000)+1)});assert.equal(r.res.status,200,JSON.stringify(r.data));const next=await state();const decision=next.state.records.find(rec=>rec.id===r.data.decisionId);assert.equal(decision.fields.actorName,'Synthetic Tester');assert.equal(decision.fields.recordVersion,target.version);assert.equal(decision.fields.factors,'Password + authenticator OTP');});
await test('Signing OTP replay cannot record another decision',async()=>{const s=await state();const target=s.state.records.find(r=>r.id==='CAPA-026');const r=await action('decision',{id:target.id,recordVersion:target.version,recordHash:await security.hash(JSON.stringify(target)),decision:'REQUEST_EVIDENCE',signingReason:'Reviewed',reason:'Replay denied',password:'synthetic-only-password-123',otp:await security.otp(secret,Math.floor(Date.now()/30000)+1)});assert.equal(r.res.status,400);assert.match(r.data.error,/already used/);});
await test('Controlled export blocked on unresolved evidence; unapproved packet succeeds',async()=>{const denied=await action('export',{id:'CAPA-026',controlled:true});assert.equal(denied.res.status,400);const allowed=await action('export',{id:'CAPA-026',controlled:false});assert.equal(allowed.res.status,200);assert.equal(allowed.data.packet.controlled,false);await state();});
await test('Source change invalidates quality and AI dependencies without rewriting decisions',async()=>{const before=await state();const decisions=JSON.stringify(before.state.records.filter(r=>r.kind==='human_decisions'));const original=before.state.records.find(r=>r.id==='SRC-SOP-014');const r=await action('edit',{id:original.id,recordVersion:original.version,fields:{text:original.fields.text+'\nVersioned additional requirement must be reviewed.'},reason:'Synthetic source change'});assert.equal(r.res.status,200);const after=await state();assert.equal(after.state.records.find(r=>r.id==='EVT-OOS-026').status,'STALE');assert.equal(after.state.records.find(r=>r.id==='AI-QA-01').status,'SUSPENDED');assert.equal(JSON.stringify(after.state.records.filter(r=>r.kind==='human_decisions')),decisions);});
await test('Historical snapshot reconstructs a pre-change version',async()=>{const res=await handle(env,new Request('https://ledger.test/api/ledger/history?workspaceId='+wid+'&revision=1',{headers:{cookie}}),['history']);const h=await res.json();assert.equal(res.status,200);assert.equal(h.state.records.length,0);assert.equal(h.hash,await security.hash(JSON.stringify(h.state)));});
await test('Unrelated user cannot read tenant workspace',async()=>{const signup=await request('signup',{name:'Other Tenant',email:'other@example.invalid',password:'other-synthetic-password-123',syntheticConsent:true},false);otherCookie=signup.res.headers.get('set-cookie').split(';')[0];otherCsrf=signup.data.csrf;const res=await handle(env,new Request('https://ledger.test/api/ledger/state?workspaceId='+wid,{headers:{cookie:otherCookie}}),['state']);assert.equal(res.status,403);});
await test('Encrypted provider value round trips without plaintext storage',async()=>{const value=await security.seal('fake-test-provider-key',env.LQ_ENCRYPTION_KEY);assert(!value.includes('fake-test'));assert.equal(await security.unseal(value,env.LQ_ENCRYPTION_KEY),'fake-test-provider-key');});
await test('Provider transient failures use initial attempt plus three bounded retries',async()=>{const attempts=[];let calls=0;await assert.rejects(()=>callModel('test-only','test-model',[],async x=>attempts.push(x),async()=>{calls++;return new Response('{}',{status:503});}));assert.equal(calls,4);assert.equal(attempts.length,4);assert(attempts.every(a=>a.status==='FAILED'));});
await test('Provider authorization failure does not retry',async()=>{let calls=0;await assert.rejects(()=>callModel('test-only','test-model',[],async()=>{},async()=>{calls++;return new Response('{}',{status:401});}));assert.equal(calls,1);});
await test('Model candidate cannot replace exact source text or approve a decision',async()=>{const s=engine.scenario();assert(!engine.validateCandidate(s,{facts:[{sourceId:'SRC-SOP-014',version:1,statement:'all compliant',span:'all compliant'}]}).valid);assert(!engine.validateCandidate(s,{facts:[],approval:true}).valid);});
await test('Owner assignment retains administration while read-only membership cannot save',async()=>{const r=await action('member',{email:'fixture@example.invalid',roles:['QA Reviewer','AI Reviewer'],syntheticAcknowledgement:true});assert.equal(r.res.status,200);assert((await state()).roles.includes('Owner'));const other=sqlite.prepare('SELECT id FROM users WHERE email=?').get('other@example.invalid');const own=sqlite.prepare('SELECT owner_id FROM workspaces WHERE id=?').get(wid);sqlite.prepare('INSERT INTO members(id,workspace_id,user_id,roles) VALUES(?,?,?,?)').run('READONLY-TEST',wid,other.id,JSON.stringify(['Read Only']));const sessionRow=sqlite.prepare('SELECT * FROM sessions WHERE user_id=?').get(other.id);const rDenied=await handle(env,new Request('https://ledger.test/api/ledger/action',{method:'POST',headers:{origin:'https://ledger.test',cookie:otherCookie,'x-lq-csrf':otherCsrf},body:JSON.stringify({action:'event',workspaceId:wid,expectedRevision:revision,operationKey:crypto.randomUUID()})}),['action']);assert.equal(rDenied.status,403);});
await test('Binary transcription revision retains exact original bytes',async()=>{const bytes=Uint8Array.from([137,80,78,71,13,10,26,10,1,2,3]);const created=await action('source',{title:'Synthetic image original',purpose:'Fixture',permission:true,text:'candidate text',base64:Buffer.from(bytes).toString('base64'),contentType:'image/png',filename:'fixture.png'});assert.equal(created.res.status,200);let st=await state();const old=st.state.records.find(r=>r.id===created.data.recordId);const edited=await action('edit',{id:old.id,recordVersion:old.version,fields:{text:'human corrected candidate text'},reason:'Fixture original retention'});assert.equal(edited.res.status,200);st=await state();const next=st.state.records.find(r=>r.id===old.id);assert.equal(next.fields.objectKey,old.fields.objectKey);assert.equal(next.hash,old.hash);assert(next.fields.transcriptionObjectKey);assert.deepEqual(blobs.get(next.fields.objectKey),bytes);const denied=await action('vision',{id:old.id});assert.equal(denied.res.status,400);assert.match(denied.data.error,/permission|model/i);});
await test('Frozen case rejects invented expected text before any inference',async()=>{const r=await action('evaluation-case',{sourceId,title:'Bad expectation',task:'Test',expectedSpans:'Invented claim'});assert.equal(r.res.status,400);assert.match(r.data.error,/exact source/i);});
await test('Expired intended use cannot be approved even with old passing tests',async()=>{const st=engine.scenario();const use=st.records.find(r=>r.id==='AI-QA-01');use.gaps=[];use.sourceIds=[];use.fields.expires='2000-01-01';assert.throws(()=>engine.assertDecision(st,use,'APPROVED'),/Expired/);});
let caseId;
await test('Signed frozen test case is bound to exact current source and reviewer',async()=>{const realNow=Date.now;const shifted=realNow()+65000;Date.now=()=>shifted;try{const st=await state();const src=st.state.records.find(r=>r.id===sourceId);const r=await action('evaluation-case',{sourceId,title:'Exact source fixture',task:'State the record-retention requirement.',expectedSpans:'The operator must retain the original value.',subgroup:'Source fidelity',critical:true,password:'synthetic-only-password-123',otp:await security.otp(secret),reason:'Reviewed synthetic fixture'});assert.equal(r.res.status,200,JSON.stringify(r.data));const after=await state();const c=after.state.testCases.at(-1);caseId=c.id;assert.equal(c.sourceHash,src.hash);assert.equal(c.sourceVersion,src.version);assert.equal(c.frozen,true);assert(c.reviewedBy);}finally{Date.now=realNow;}});
await test('Paired evaluation executes two models twice and saves exact expectations',async()=>{const configured=await action('settings',{providerKey:'fake-provider-key-for-mock-only',providerConsent:true,model:'mock-author',reviewerModel:'mock-reviewer',visionModel:'mock-vision'});assert.equal(configured.res.status,200);await state();const originalFetch=globalThis.fetch;let calls=0;const models=[];globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://api.groq.com/openai/v1/chat/completions');const body=JSON.parse(opts.body);models.push(body.model);calls++;return Response.json({choices:[{message:{content:JSON.stringify({facts:[{sourceId,version:1,statement:'The operator must retain the original value.',span:'The operator must retain the original value.'}],gaps:[]})}}],usage:{total_tokens:15}});};try{const r=await action('paired-evaluation',{id:caseId});assert.equal(r.res.status,200,JSON.stringify(r.data));const st=await state();const result=st.state.records.find(x=>x.id===r.data.recordId);assert.equal(calls,4);assert.deepEqual(models,['mock-author','mock-author','mock-reviewer','mock-reviewer']);assert.equal(result.fields.passed,4);assert.equal(result.fields.denominator,4);assert.equal(result.fields.criticalFailures,0);}finally{globalThis.fetch=originalFetch;}});
await test('Extra exact-source facts cannot pass a frozen answer set or escape HOLD',async()=>{await state();const before=await state();const src=before.state.records.find(r=>r.id===sourceId);const originalFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({choices:[{message:{content:JSON.stringify({facts:[{sourceId,version:src.version,statement:'The operator must retain the original value.',span:'The operator must retain the original value.'},{sourceId,version:src.version,statement:String(src.fields.text),span:String(src.fields.text)}],gaps:[]})}}]});try{const r=await action('paired-evaluation',{id:caseId});assert.equal(r.res.status,200,JSON.stringify(r.data));const st=await state();const result=st.state.records.find(x=>x.id===r.data.recordId);assert.equal(result.status,'HOLD');assert.equal(result.fields.passed,0);assert.equal(result.fields.criticalFailures,4);}finally{globalThis.fetch=originalFetch;}});
await test('Frozen answers require exact source, version, complete set and no duplicates',async()=>{const c={sourceId:'S1',sourceVersion:2,expectedAbstain:false,expectedSpans:['First supported line.','Second supported line.']};const f=c.expectedSpans.map(span=>({sourceId:'S1',version:2,statement:span,span}));assert(engine.matchesFrozenCase(c,f));assert(!engine.matchesFrozenCase(c,f.slice(0,1)));assert(!engine.matchesFrozenCase(c,[...f,f[0]]));assert(!engine.matchesFrozenCase(c,f.map(x=>({...x,sourceId:'OTHER'}))));assert(!engine.matchesFrozenCase(c,f.map(x=>({...x,version:1}))));assert(engine.matchesFrozenCase({...c,expectedAbstain:true},[]));assert(!engine.matchesFrozenCase({...c,expectedAbstain:true},f));});
await test('Malformed, duplicate, stale or gapped candidate citations fail safely',async()=>{const s=engine.scenario(),source=s.records.find(r=>r.kind==='controlled_sources'&&r.status==='CURRENT'),span=source.fields.text.split('\n')[0];const f={sourceId:source.id,version:source.version,statement:span,span};assert(engine.validateCandidate(s,{facts:[f]}).valid);assert(!engine.validateCandidate(s,{facts:[null]}).valid);assert(!engine.validateCandidate(s,{facts:[f,f]}).valid);source.gaps=['Original unavailable.'];assert(!engine.validateCandidate(s,{facts:[f]}).valid);source.gaps=[];source.status='STALE';assert(!engine.validateCandidate(s,{facts:[f]}).valid);});
await test('Paired provider failures remain failed critical cases and save first break',async()=>{const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response('{}',{status:401});try{const r=await action('paired-evaluation',{id:caseId});assert.equal(r.res.status,200,JSON.stringify(r.data));const st=await state();const result=st.state.records.find(x=>x.id===r.data.recordId);assert.equal(result.status,'HOLD');assert.equal(result.fields.passed,0);assert.equal(result.fields.criticalFailures,4);assert.equal(result.fields.firstFailure.firstFailure,'PROVIDER');assert.equal(result.fields.firstFailure.rootCause,'UNKNOWN');}finally{globalThis.fetch=originalFetch;}});
let backup;
await test('Evidence backup includes current and historical originals with checksums',async()=>{const r=await handle(env,new Request('https://ledger.test/api/ledger/backup?workspaceId='+wid,{headers:{cookie}}),['backup']);backup=await r.json();assert.equal(r.status,200,JSON.stringify(backup));assert.equal(backup.format,'LQ_BACKUP_V2');assert(backup.originals.length>3);assert(backup.histories.length>2);for(const o of backup.originals)assert.equal(o.hash,await security.hash(Uint8Array.from(Buffer.from(o.base64,'base64')).buffer));});
await test('Corrupt original blocks restore without overwriting workspace',async()=>{const bad=structuredClone(backup);bad.originals[0].hash='corrupt';const r=await action('restore-backup',{backup:bad});assert.equal(r.res.status,400);assert.match(r.data.error,/checksum/i);});
await test('Verified copy restore preserves files, scopes permissions and is idempotent',async()=>{const key=crypto.randomUUID();const r=await action('restore-backup',{backup},key);assert.equal(r.res.status,200,JSON.stringify(r.data));assert.notEqual(r.data.restoredWorkspaceId,wid);await state();const res=await handle(env,new Request('https://ledger.test/api/ledger/state?workspaceId='+r.data.restoredWorkspaceId,{headers:{cookie}}),['state']);const copy=await res.json();assert.equal(res.status,200);assert.equal(copy.state.policy.providerConsent,false);assert.deepEqual(copy.roles,['Owner','Investigator']);for(const source of copy.state.records.filter(r=>r.kind==='controlled_sources'))assert(blobs.has(source.fields.objectKey));assert(blobs.has(r.data.restoredWorkspaceId+'/import/verified-backup.json'));const again=await action('restore-backup',{backup},key);assert.equal(again.data.replayed,true);});

await test('Gemini transport uses fixed endpoint, hidden header, JSON and actual usage',async()=>{const attempts=[];const r=await callModel('mock-secret','gemini-fixture',[{role:'system',content:'JSON only'},{role:'user',content:[{type:'text',text:'Synthetic image'},{type:'image_url',image_url:{url:'data:image/png;base64,AQID'}}]}],async a=>attempts.push(a),async(url,opts)=>{assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-fixture:generateContent');assert.equal(opts.headers['x-goog-api-key'],'mock-secret');assert(!url.includes('mock-secret'));assert(!opts.headers.Authorization);const b=JSON.parse(opts.body);assert.equal(b.generationConfig.responseMimeType,'application/json');assert.equal(b.contents[0].parts[1].inlineData.mimeType,'image/png');return Response.json({candidates:[{content:{parts:[{text:'{"ready":true}'}]}}],usageMetadata:{totalTokenCount:19}});},'gemini');assert(r.output.ready);assert.equal(r.usage.totalTokenCount,19);assert.equal(attempts[0].provider,'gemini');});
await test('Gemini discovery filters unsupported models and does not leak credentials',async()=>{const models=await geminiModels('mock-secret',async(url,opts)=>{assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000');assert.equal(opts.headers['x-goog-api-key'],'mock-secret');return Response.json({models:[{name:'models/gemini-flash-fixture',supportedGenerationMethods:['generateContent']},{name:'models/gemini-flash-lite-latest',supportedGenerationMethods:['generateContent']},{name:'models/gemini-tts-fixture',supportedGenerationMethods:['generateContent']},{name:'models/other',supportedGenerationMethods:['generateContent']}]});});assert.deepEqual(models.map(m=>m.id),['gemini-flash-fixture']);env.GEMINI_API_KEY='mock-env-gemini';assert.equal(await providerKey(env,wid,'gemini'),'mock-env-gemini');assert.equal(await providerKey(env,wid,'groq'),'fake-provider-key-for-mock-only');});
await test('Gemini connection consent and two live mocked model results are saved',async()=>{await state();const denied=await action('connect-gemini',{providerConsent:false});assert.equal(denied.res.status,400);const oldFetch=globalThis.fetch;globalThis.fetch=async(url,opts)=>url.endsWith('pageSize=1000')?Response.json({models:['gemini-flash-lite-fixture','gemini-flash-fixture'].map(id=>({name:'models/'+id,supportedGenerationMethods:['generateContent']}))}):Response.json({candidates:[{content:{parts:[{text:JSON.stringify({ready:true,marker:'LQ_SYNTHETIC_CONNECTION'})}]}}],usageMetadata:{totalTokenCount:8}});try{const r=await action('connect-gemini',{providerConsent:true});assert.equal(r.res.status,200,JSON.stringify(r.data));assert.equal(r.data.connected,true);assert.notEqual(r.data.models[0],r.data.models[1]);const st=await state();assert.equal(st.state.policy.provider,'gemini');assert(st.state.records.find(x=>x.id===r.data.recordId).fields.observations.every(x=>x.pass&&x.attempts.length===1));}finally{globalThis.fetch=oldFetch;}});
await test('Two model aliases resolving to one underlying model cannot claim independent connection',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async(url)=>url.endsWith('pageSize=1000')?Response.json({models:['gemini-flash-lite-fixture','gemini-flash-fixture'].map(id=>({name:'models/'+id,supportedGenerationMethods:['generateContent']}))}):Response.json({modelVersion:'gemini-same-underlying',candidates:[{content:{parts:[{text:JSON.stringify({ready:true,marker:'LQ_SYNTHETIC_CONNECTION'})}]}}]});try{const r=await action('connect-gemini',{providerConsent:true});assert.equal(r.res.status,200);assert.equal(r.data.connected,false);await state();}finally{globalThis.fetch=oldFetch;}});
await test('Unavailable discovered reviewer falls back boundedly and preserves failed attempts',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async(url)=>url.endsWith('pageSize=1000')?Response.json({models:['gemini-flash-lite-fixture','gemini-flash-z-fixture','gemini-flash-a-fixture'].map(id=>({name:'models/'+id,supportedGenerationMethods:['generateContent']}))}):url.includes('flash-z-fixture')?new Response('{}',{status:401}):Response.json({modelVersion:url.split('/').at(-1).split(':')[0],candidates:[{content:{parts:[{text:JSON.stringify({ready:true,marker:'LQ_SYNTHETIC_CONNECTION'})}]}}]});try{const r=await action('connect-gemini',{providerConsent:true});assert.equal(r.res.status,200);assert(r.data.connected);assert.equal(r.data.models[1],'gemini-flash-a-fixture');const st=await state();const check=st.state.records.find(x=>x.id===r.data.recordId);assert.equal(check.fields.observations.length,3);assert(check.fields.observations.some(o=>!o.pass&&o.attempts[0].httpStatus===401));}finally{globalThis.fetch=oldFetch;}});
await test('Gemini saved planner, specialists and independent review preserve HOLD',async()=>{const oldFetch=globalThis.fetch;let calls=0;const models=new Set();globalThis.fetch=async(url,opts)=>{assert(url.startsWith('https://generativelanguage.googleapis.com/v1beta/models/gemini-'));models.add(url.split('/').at(-1).split(':')[0]);calls++;const b=JSON.parse(opts.body);const prompt=b.systemInstruction.parts[0].text;const output=prompt.includes('bounded planner')?{specialists:['Deviation / OOS'],reason:'Review recorded conflict'}:prompt.includes('Independent evidence reviewer')?{supported:true,conflicts:[],gaps:['Human review remains required']}:{facts:[],gaps:['Conflicting original requires human review'],recommendation:'HOLD'};return Response.json({candidates:[{content:{parts:[{text:JSON.stringify(output)}]}}],usageMetadata:{totalTokenCount:21}});};try{const r=await action('agent',{id:'EVT-OOS-026',mode:'live'});assert.equal(r.res.status,200,JSON.stringify(r.data));assert.equal(r.data.status,'HOLD');const st=await state();const job=st.state.jobs.at(-1);assert.equal(job.phase,4);assert.equal(job.reviewer.output.supported,true);assert.equal(job.reviewer.independence.pass,true);assert.equal(models.size,2);assert(calls>=3);assert(job.attempts.filter(a=>a.provider).every(a=>a.provider==='gemini'));assert.notEqual(st.state.records.find(x=>x.id==='EVT-OOS-026').status,'APPROVED');}finally{globalThis.fetch=oldFetch;}});
await test('Live reviewer resolving to the author model is recorded as failed independence and HOLD',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);const prompt=b.systemInstruction.parts[0].text;const output=prompt.includes('bounded planner')?{specialists:['Deviation / OOS'],reason:'Review conflict'}:prompt.includes('Independent evidence reviewer')?{supported:true,conflicts:[],gaps:[]}:{facts:[],gaps:[],recommendation:'Human review'};return Response.json({modelVersion:'gemini-same-underlying',candidates:[{content:{parts:[{text:JSON.stringify(output)}]}}]});};try{const r=await action('agent',{id:'EVT-OOS-026',mode:'live'});assert.equal(r.res.status,200);assert.equal(r.data.status,'HOLD');const st=await state();assert.equal(st.state.jobs.at(-1).reviewer.independence.pass,false);}finally{globalThis.fetch=oldFetch;}});
await test('Gemini provider auth failures remain failed connection records',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async(url)=>url.endsWith('pageSize=1000')?Response.json({models:['gemini-flash-lite-fixture','gemini-flash-fixture'].map(id=>({name:'models/'+id,supportedGenerationMethods:['generateContent']}))}):new Response('{}',{status:403});try{const r=await action('connect-gemini',{providerConsent:true});assert.equal(r.res.status,200);assert.equal(r.data.connected,false);const st=await state();const check=st.state.records.find(x=>x.id===r.data.recordId);assert.equal(check.status,'EXHAUSTED');assert(check.fields.observations.every(o=>o.attempts.length===1&&o.attempts[0].status==='FAILED'));}finally{globalThis.fetch=oldFetch;}});

await test('Provider redirects cannot forward credentials and are not retried',async()=>{let calls=0;const attempts=[];await assert.rejects(()=>callModel('fixture-secret','fixture-author',[],async a=>attempts.push(a),async(url,opts)=>{calls++;assert.equal(opts.redirect,'manual');return new Response(null,{status:302,headers:{location:'https://untrusted.test/'}});}));assert.equal(calls,1);assert.equal(attempts[0].status,'FAILED');assert(!JSON.stringify(attempts).includes('fixture-secret'));});
await test('Valid-looking truncated JSON cannot count as a successful AI result',async()=>{let calls=0;const attempts=[];await assert.rejects(()=>callModel('fixture-secret','fixture-author',[],async a=>attempts.push(a),async()=>{calls++;return Response.json({choices:[{finish_reason:'length',message:{content:'{"facts":[]}'}}]});}));assert.equal(calls,1);assert(attempts.every(a=>a.status==='FAILED'));});
await test('Transient independent-reviewer outage can use only bounded configured alternatives',async()=>{const oldFetch=globalThis.fetch;const s=engine.emptyWorkspace('fixture');s.policy={...s.policy,provider:'gemini',providerConsent:true,model:'gemini-3.5-flash-lite',reviewerModel:'gemini-3.8-flash',reviewerFallbacks:['gemini-3.6-flash','gemini-3.5-flash-lite']};const attempts=[];let count=0;globalThis.fetch=async(url,opts)=>{count++;const b=JSON.parse(opts.body);assert.equal(b.generationConfig.thinkingConfig.thinkingLevel,'low');if(url.includes('gemini-3.8-flash:'))return new Response('{}',{status:503});return Response.json({modelVersion:'gemini-3.6-flash',candidates:[{finishReason:'STOP',content:{parts:[{text:'{"supported":true,"conflicts":[],"gaps":[]}' }]}}]});};try{const r=await reviewAI(s,[], 'mock-key',async a=>attempts.push(a));assert.equal(r.usedFallback,true);assert.equal(r.actualModel,'gemini-3.6-flash');assert.equal(count,5);assert.equal(attempts.filter(a=>a.status==='FAILED').length,4);assert(!attempts.some(a=>a.model===s.policy.model));assert.equal(s.policy.reviewerModel,'gemini-3.8-flash');}finally{globalThis.fetch=oldFetch;}});
await test('Authentication denial cannot be bypassed through another reviewer model',async()=>{const oldFetch=globalThis.fetch;const s=engine.emptyWorkspace('fixture');s.policy={...s.policy,provider:'gemini',model:'gemini-author',reviewerModel:'gemini-reviewer',reviewerFallbacks:['gemini-alternative']};let calls=0;globalThis.fetch=async()=>{calls++;return new Response('{}',{status:401});};try{await assert.rejects(()=>reviewAI(s,[], 'mock-key',async()=>{}));assert.equal(calls,1);}finally{globalThis.fetch=oldFetch;}});
await test('Empty live facts cannot be promoted to a completed supported outcome',async()=>{await state();const oldFetch=globalThis.fetch;globalThis.fetch=async(url,opts)=>{const b=JSON.parse(opts.body),prompt=b.systemInstruction.parts[0].text;const output=prompt.includes('bounded planner')?{specialists:['Deviation / OOS'],reason:'No facts'}:prompt.includes('Independent evidence reviewer')?{supported:true,conflicts:[],gaps:[]}:{facts:[],gaps:[],recommendation:'Human review'};return Response.json({modelVersion:url.split('/').at(-1).split(':')[0],candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(output)}]}}]});};try{const r=await action('agent',{id:'EVT-OOS-026',mode:'live'});assert.equal(r.res.status,200);assert.equal(r.data.status,'HOLD');}finally{globalThis.fetch=oldFetch;}});
await test('Logout invalidates the app session',async()=>{const r=await request('logout',{});assert.equal(r.res.status,200);const s=await request('session');assert.equal(s.data.user,null);});
mkdirSync('docs/verification',{recursive:true});writeFileSync('docs/verification/integration-results.json',JSON.stringify({at:new Date().toISOString(),scope:'D1-compatible SQLite/R2-memory API integration + synthetic controls. Not deployed/browser/professional validation.',passed:receipts.length,results:receipts},null,2));console.log('Completed '+receipts.length+' meaningful integration checks.');
