import {type Item,type State,newItem,now,uid} from './types';
export function find(s:State,id:string){const r=s.records.find(r=>r.id===id);if(!r)throw new Error('Record not found in this workspace.');return r;}
export function dependents(s:State,id:string){const found=new Set<string>();let frontier=[id];while(frontier.length){const next:string[]=[];for(const r of s.records){const edges=s.records.filter(e=>e.kind==='dependency_edges'&&frontier.includes(e.fields.from)).map(e=>e.fields.to);if((r.sourceIds.some(x=>frontier.includes(x))||edges.includes(r.id))&&!found.has(r.id)&&r.id!==id){found.add(r.id);next.push(r.id);}}frontier=next;}return [...found];}
export function invalidate(s:State,id:string){const ids=dependents(s,id);for(const r of s.records.filter(r=>ids.includes(r.id))){if(['human_decisions','audit_events','exports'].includes(r.kind))continue;r.fields.previousStatus=r.status;r.status=r.kind==='ai_uses'||r.kind==='release_passports'?'SUSPENDED':'STALE';r.gaps=[...new Set([...r.gaps,'Dependency changed: '+id+'. Fresh checks and human review required.'])];r.version++;r.updated=now();}s.outbox.push({id:uid('NOTICE'),created:now(),status:'PENDING',type:'SOURCE_CHANGED',affected:ids});return ids;}
export function evidenceGaps(s:State,r:Item){const gaps=[...r.gaps];for(const id of r.sourceIds){const source=s.records.find(x=>x.id===id);if(!source)gaps.push('Missing linked record '+id);else if(['STALE','HOLD','UNKNOWN','SUSPENDED','REVOKED','EXPIRED'].includes(source.status))gaps.push('Linked record '+id+' is '+source.status);}return [...new Set(gaps)];}
export function grounded(text:string,source:Item,span:string){return !!span&&!!text&&String(source.fields.text||'').includes(span)&&text===span;}
export function numericConflict(values:{value:number;unit:string;batch:string;method:string}[]){return values.length>1&&(new Set(values.map(x=>`${x.value}|${x.unit}|${x.batch}|${x.method}`)).size>1);}
export function canClose(s:State,r:Item){return r.kind==='capa_actions'&&!!r.fields.implementationEvidence&&!!r.fields.effectivenessEvidence&&!!r.fields.humanEstablishedCause&&evidenceGaps(s,r).length===0;}
export function extract(s:State,source:Item){const text=String(source.fields.text||'');if(!text.trim())throw new Error('Source needs readable text or an approved extraction.');return text.split('\n').map(x=>x.trim()).filter(x=>x&&/(shall|must|required|<=|≥|≤|limit|acceptance|not exceed)/i.test(x)).slice(0,30).map(span=>newItem('requirements',span.slice(0,110),{statement:span,span,offset:text.indexOf(span),sourceVersion:source.version,sourceHash:source.hash,confidence:'Exact text; applicability requires review'},[source.id]));}
export function assertDecision(s:State,r:Item,decision:string){if(!['APPROVED','REJECTED','REQUEST_EVIDENCE','REVISED','SUSPENDED','REVOKED'].includes(decision))throw new Error('Unsupported decision.');if(decision==='APPROVED'){if(evidenceGaps(s,r).length)throw new Error('Open evidence gaps block approval.');if(r.kind==='requirements'){const source=s.records.find(x=>x.id===r.sourceIds[0]);if(!source||r.fields.sourceVersion!==source.version||!grounded(r.fields.statement,source,r.fields.span))throw new Error('Requirement needs exact support from the current source revision.');}if(r.kind==='sop_mappings'){const sop=s.records.find(x=>x.id===r.fields.sopId&&x.kind==='controlled_sources');const req=s.records.find(x=>x.id===r.fields.requirementId&&x.kind==='requirements');if(!r.fields.rationale||r.fields.coverage!=='SUPPORTED'||!sop||!req||!r.fields.sopSpan||!String(sop.fields.text||'').includes(r.fields.sopSpan)||!r.sourceIds.includes(sop.id))throw new Error('SOP mapping needs current requirement, exact SOP excerpt, linked source, supported coverage and rationale.');}if(r.kind==='training_impacts'&&(!r.fields.completionEvidence||!r.fields.sourceVersion||!r.sourceIds.some(id=>s.records.find(x=>x.id===id&&x.version===r.fields.sourceVersion))))throw new Error('Training completion evidence and exact version required.');if(r.kind==='capa_actions'&&!canClose(s,r))throw new Error('CAPA closure requires human-established cause, implementation and effectiveness evidence.');if(r.kind==='ai_uses'&&r.fields.expires&&r.fields.expires<now().slice(0,10))throw new Error('Expired intended use cannot be approved.');if(r.kind==='ai_uses'){const current=s.records.filter(x=>x.kind==='evaluation_runs'&&x.sourceIds.includes(r.id)&&x.fields.sourceVersion===r.version).at(-1);if(!current||current.fields.criticalFailures!==0)throw new Error('Latest current-revision evaluation evidence must pass; old passing runs cannot hide a new failure.');}if(['quality_events','investigation_records'].includes(r.kind)&&(!r.fields.humanEstablishedCause||!r.fields.humanDisposition))throw new Error('Named human root-cause and disposition rationale required.');}}
export function validateCandidate(s:State,c:any){if(!c||!Array.isArray(c.facts)||c.facts.length>30)return {valid:false,gaps:['Invalid candidate schema.']};const gaps:string[]=[];const seen=new Set<string>();for(const f of c.facts){if(!f||typeof f!=='object'){gaps.push('Invalid candidate fact.');continue;}const source=s.records.find(r=>r.id===f.sourceId&&r.kind==='controlled_sources');if(!source||source.status!=='CURRENT'||source.gaps.length||f.version!==source.version||!grounded(f.statement,source,f.span))gaps.push('Unsupported candidate citation '+String(f.sourceId||'missing'));const key=JSON.stringify([f.sourceId,f.version,f.span]);if(seen.has(key))gaps.push('Duplicate candidate citation.');seen.add(key);}if(c.disposition||c.approval||c.rootCauseEstablished)gaps.push('Agent attempted a prohibited human decision.');return {valid:!gaps.length,gaps};}
/** An exact reviewer answer set is required; a subset match cannot hide extra facts. */
export function matchesFrozenCase(c:any,facts:any){if(!Array.isArray(facts))return false;if(c.expectedAbstain)return facts.length===0;const expected=c.expectedSpans;if(!Array.isArray(expected)||!expected.length||new Set(expected).size!==expected.length||facts.length!==expected.length)return false;return facts.every((f:any)=>f&&f.sourceId===c.sourceId&&f.version===c.sourceVersion&&f.statement===f.span&&expected.includes(f.span))&&new Set(facts.map((f:any)=>f.span)).size===expected.length;}
function denied(f:()=>unknown){try{f();return false;}catch{return true;}}
export function evaluationPack(){const s=scenario('evaluation',false);const source=find(s,'SRC-SOP-014');const capa=find(s,'CAPA-026');const use=find(s,'AI-QA-01');const changed=structuredClone(s);invalidate(changed,source.id);
 const cases=[
 ['E01','Grounding',true,!validateCandidate(s,{facts:[{sourceId:source.id,version:source.version,statement:'unsupported',span:'unsupported'}]}).valid,true,'Unsupported statement rejected.'],
 ['E02','Units',true,numericConflict([{value:10,unit:'mg',batch:'B1',method:'HPLC'},{value:10,unit:'g',batch:'B1',method:'HPLC'}]),true,'Unit mutation cannot merge.'],
 ['E03','Batch identity',true,numericConflict([{value:99,unit:'%',batch:'B1',method:'HPLC'},{value:99,unit:'%',batch:'B2',method:'HPLC'}]),true,'Different batches remain distinct.'],
 ['E04','Evidence removal',true,!validateCandidate(s,{facts:[{sourceId:'removed',version:1,statement:'x',span:'x'}]}).valid,true,'Removed citation rejects candidate.'],
 ['E05','Operator mutation',false,grounded('Sample storage temperature shall be < 25 C.',source,'Sample storage temperature shall be < 25 C.'),true,'Changing <= to < loses exact support.'],
 ['E06','Version change','STALE',find(changed,'EVT-OOS-026').status,true,'Dependent quality record becomes stale.'],
 ['E07','Prohibited decision',false,validateCandidate(s,{facts:[],approval:true}).valid,true,'Candidate cannot grant approval.'],
 ['E08','CAPA effectiveness',true,denied(()=>assertDecision(s,capa,'APPROVED')),true,'Missing effectiveness blocks closure.'],
 ['E09','Assessor conflict',true,denied(()=>assertDecision(s,find(s,'EVT-OOS-026'),'APPROVED')),true,'Unresolved assay conflict blocks acceptance.'],
 ['E10','Missing context',true,evidenceGaps(s,use).length>0,false,'Intended-use uncertainty remains visible.'],
 ['E11','Deterministic consistency',true,JSON.stringify(extract(s,source).map(x=>x.fields.statement))===JSON.stringify(extract(s,source).map(x=>x.fields.statement)),false,'Not live model repeatability.'],
 ['E12','First failure','LAB_RECORD_CONFLICT',s.records.find(r=>r.kind==='investigation_records')?.fields.firstFailure,true,'First evidenced break retained.']
 ];return cases.map(([id,family,expected,actual,critical,note])=>({id,family,expected,actual,critical,note,pass:expected===actual,mode:'Executed deterministic control fixture',observedAt:now()}));}
export function evaluate(s:State,target:Item){const cases=evaluationPack();return newItem('evaluation_runs','Critical-control challenge run',{cases,denominator:cases.length,passed:cases.filter(c=>c.pass).length,criticalFailures:cases.filter(c=>c.critical&&!c.pass).length,scope:'Executed synthetic control checks; not model quality, regulatory accuracy or independent validation.',sourceVersion:target.version,firstFailure:cases.find(c=>!c.pass)?.id||null},[target.id],cases.every(c=>c.pass)?'CONTROL CHECKS PASSED':'HOLD');}
export function deterministicSpecialist(s:State,name:string,target:Item){const gaps=evidenceGaps(s,target);return {specialist:name,mode:'Deterministic',targetId:target.id,version:target.version,status:gaps.length?'HOLD':'REVIEW REQUIRED',facts:target.sourceIds.map(id=>s.records.find(r=>r.id===id)).filter(r=>r?.kind==='controlled_sources').map(r=>({sourceId:r!.id,version:r!.version,span:target.kind==='assessments'?(String(r!.fields.text||'').split('\n').find(line=>/"(?:batch|value|parameter|productId|sourceId|revision)"/.test(line))||String(r!.fields.text||'').split('\n')[0]):String(r!.fields.text||'').split('\n')[0],hash:r!.hash})),gaps,recommendation:target.kind==='assessments'?String(target.fields.summary||'Review the saved typed checks and source gaps; no human approval is granted.'):name==='CAPA / effectiveness'?'Human-established cause and implementation/effectiveness evidence required.':name==='Deviation / OOS'?'Keep hypotheses separate from established cause. Named QA decides disposition.':'Check exact source support and current context. Human review remains required.'};}
export function scenario(id='public',withEval=true):State{const state:State={workspace:{id,name:'Drug Q · synthetic assurance workspace',synthetic:true,productId:'PRODUCT-LQ-001',siteId:'SITE-LQ-DEMO'},records:[],jobs:[],outbox:[],policy:{providerConsent:false,model:'',reviewerModel:'',visionModel:'',retentionDays:365},corrections:[],mappings:[]};
 const source=newItem('controlled_sources','SOP-QC-014 · assay & investigation',{filename:'SOP-QC-014-v3.txt',text:'SOP-QC-014 version 3 — synthetic portfolio exercise.\nAcceptance: assay must be 95.0–105.0% of label claim.\nSample storage temperature shall be <= 25 C.\nA laboratory result outside acceptance requires an investigation.\nRepeat testing must have an approved rationale; the original result shall be retained.\nCAPA closure requires implementation and effectiveness evidence.\nA named QA reviewer must review the exact record version.',permission:true,purpose:'Synthetic quality review',effectiveDate:'2026-10-01'},[],'CURRENT');source.id='SRC-SOP-014';source.hash='synthetic-fixture';
 const lab=newItem('controlled_sources','Batch LQ-026 · original assay record',{filename:'LQ-026-assay.txt',text:'Synthetic laboratory record. Batch LQ-026. Method HPLC-Q-02. Original assay: 94.2%. A transcribed worksheet lists 99.1% for the same batch and method. No approved repeat-test rationale supplied.',values:[{value:94.2,unit:'%',batch:'LQ-026',method:'HPLC-Q-02'},{value:99.1,unit:'%',batch:'LQ-026',method:'HPLC-Q-02'}],permission:true,purpose:'Synthetic OOS investigation',effectiveDate:'2026-10-02'},[],'CURRENT');lab.id='SRC-LAB-026';
 state.records.push(source,lab,...extract(state,source));
 const event=newItem('quality_events','OOS-026 · conflicting assay values',{eventType:'OOS',batch:'LQ-026',method:'HPLC-Q-02',originalValue:94.2,transcribedValue:99.1,unit:'%',severity:'High',likelihood:'Not established',confidence:'Evidence incomplete',rootCause:'UNKNOWN',disposition:'Not decided',chronology:[{date:'2026-10-02',event:'Original assay recorded at 94.2%.'},{date:'2026-10-03',event:'99.1% transcription identified; authorized rationale absent.'}]},[source.id,lab.id],'HOLD');event.id='EVT-OOS-026';event.gaps=['Same-batch assay conflict: 94.2% versus 99.1%.','Approved investigation and repeat-test rationale unavailable.'];event.owner='Demo investigator';
 const investigation=newItem('investigation_records','OOS investigation · hypotheses, not conclusions',{hypotheses:['Transcription error — unconfirmed','Sample preparation variation — unconfirmed'],rootCause:'UNKNOWN',firstFailure:'LAB_RECORD_CONFLICT'},[event.id,lab.id],'HOLD');
 const capa=newItem('capa_actions','CAPA-026 · preserve and investigate original result',{humanEstablishedCause:'',action:'Verify original chromatogram and approved testing rationale before deciding corrective action.',implementationEvidence:'',effectivenessEvidence:'',due:'2026-10-20'},[event.id],'HOLD');capa.id='CAPA-026';capa.gaps=['Human-established cause and effectiveness evidence missing.'];capa.owner='Demo process owner';
 const use=newItem('ai_uses','AI-QA-01 · investigation summary support',{intendedUse:'Prepare source-grounded candidate summaries only.',excludedUse:'Root cause, batch disposition, CAPA closure, regulatory decisions.',model:'Not configured',promptVersion:'v1',policyVersion:'v1',releaseState:'SUSPENDED',owner:'AI assurance owner',reviewer:'Named AI reviewer required'},[source.id,event.id],'SUSPENDED');use.id='AI-QA-01';use.gaps=['Live provider and independent intended-use qualification not established.'];
 const mapping=newItem('sop_mappings','Assay requirement → investigation process',{requirementId:state.records.find(r=>r.kind==='requirements')?.id,sopId:source.id,rationale:'Synthetic mapping to assay investigation record; coverage remains under review.',coverage:'GAP'},[source.id,event.id],'REVIEW REQUIRED');
 const training=newItem('training_impacts','QC investigator · SOP version 3',{role:'QC investigator',sourceVersion:3,completionEvidence:'',due:'2026-10-15'},[source.id],'REVIEW REQUIRED');
 const finding=newItem('quality_events','Finding-02 · repeat-test rationale absent',{eventType:'Inspection finding',batch:'LQ-026',severity:'High',likelihood:'Unknown',confidence:'Source-backed gap'},[lab.id,capa.id],'HOLD');finding.gaps=['Approved rationale absent.'];
 state.records.push(event,investigation,capa,use,mapping,training,finding);
 for(const pair of [[source.id,event.id],[lab.id,event.id],[event.id,capa.id],[source.id,use.id],[event.id,use.id],[source.id,training.id]])state.records.push(newItem('dependency_edges','Evidence dependency',{from:pair[0],to:pair[1]},pair,'CURRENT'));
 state.records.push(newItem('release_passports','AI-QA-01 · current use passport',{useId:use.id,intendedUse:use.fields.intendedUse,releaseState:'SUSPENDED',limits:'No professional qualification or regulatory release.',expires:'2026-11-01'},[use.id],'SUSPENDED'));
 if(withEval)state.records.push(evaluate(state,use));return state;}

export function emptyWorkspace(id:string,name='My quality workspace',provider:'groq'|'gemini'='groq'):State{return {workspace:{id,name,synthetic:true,productId:'NOT_SET',siteId:'NOT_SET'},records:[],jobs:[],outbox:[],policy:{provider,providerConsent:false,model:'',reviewerModel:'',visionModel:'',retentionDays:365},corrections:[],mappings:[],testCases:[]};}
