import {newItem,type Item,type State} from './types';

/** Bounded, reproducible quality checks. These never decide batch disposition. */
export const assessmentTypes = {
  'batch-record':'Batch record completeness', 'batch-quality':'Batch quality review',
  'batch-readiness':'Batch readiness', 'oot':'Out-of-trend review',
  'regulatory':'Regulatory change intake', 'sop':'SOP coverage',
  'risk':'Risk and inspection priorities', 'investigation':'Investigation / OOS checks',
  'effectiveness':'CAPA effectiveness', 'apqr':'PQR / management review',
  'model':'Model quality and subgroup review', 'data-quality':'Data quality',
  'requirements':'AI requirements mapping', 'privacy':'Data handling review',
  'improvement':'Improvement action review',
} as const;
export type AssessmentType=keyof typeof assessmentTypes;
export function assessmentSpecialists(type:AssessmentType){return type==='model'||type==='privacy'||type==='requirements'?['AI provenance','AI evaluation','Evidence / audit verifier']:type==='regulatory'||type==='sop'?['Requirement mapping','Change impact','Evidence / audit verifier']:['Deviation / OOS','CAPA / effectiveness','Change impact','Evidence / audit verifier'];}
type Check={item:string;finding:string;pass:boolean;sourceId?:string;path?:string};
type Output={checks:Check[];gaps:string[];next:string[];metrics:Record<string,unknown>;summary:string};
const badStates=['STALE','HOLD','UNKNOWN','SUSPENDED','REVOKED','EXPIRED','NEEDS REVIEW'];
const finite=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n);
const text=(x:unknown):x is string=>typeof x==='string'&&x.trim().length>0;
const iso=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const uniq=(x:string[])=>[...new Set(x)];
const bounded=(v:any,label:string,min=1,max=100):any[]=>{if(!Array.isArray(v)||v.length<min||v.length>max)throw new Error(`${label} needs ${min}–${max} entries.`);return v;};
const check=(o:Output,item:string,pass:boolean,finding:string,sourceId?:string,path?:string)=>{o.checks.push({item,pass,finding,sourceId,path});if(!pass)o.gaps.push(item+': '+finding);};
function decode(source:Item,format:string){let v:any;try{v=JSON.parse(String(source.fields.text||''));}catch{throw new Error('This check needs structured source JSON. Use the downloadable template; preserve the original source.');}if(v?.format!==format)throw new Error('Expected source format '+format+'.');return v;}
function context(s:State,o:Output,v:any,source:Item){check(o,'Product and site context',text(v.productId)&&text(v.siteId)&&v.productId===s.workspace.productId&&v.siteId===s.workspace.siteId,'Source product/site must match the configured workspace.',source.id,'productId / siteId');}

function batch(s:State,o:Output,source:Item,type:AssessmentType){
  const v=decode(source,'LQ_BATCH_V1');context(s,o,v,source);
  check(o,'Batch identity',text(v.batch),'An explicit batch ID is required.',source.id,'batch');
  const required=bounded(v.requiredSteps,'Required batch steps');
  if(required.some((x:any)=>!text(x))||new Set(required).size!==required.length)throw new Error('Required steps must be unique names.');
  const steps=bounded(v.steps,'Batch records');
  check(o,'Unique record steps',new Set(steps.map(x=>x.step)).size===steps.length,'Duplicate steps need reconciliation.',source.id,'steps');
  for(const name of required){const r=steps.find(x=>x.step===name);check(o,name,!!r&&r.observed!==null&&r.observed!==undefined&&text(r.reference)&&text(r.performedBy)&&iso(r.date),r?'Recorded value, reference, performer and valid date required.':'Required record is missing.',source.id,'steps.'+name);if(r&&r.expected!==undefined)check(o,name+' acceptance',r.observed===r.expected,'Recorded observation must match the source-stated acceptance value.',source.id,'steps.'+name);}
  o.metrics.batch=v.batch;o.metrics.requiredSteps=required.length;o.metrics.recordedSteps=required.filter(n=>steps.some(r=>r.step===n)).length;
  if(type!=='batch-record'){
    const qc=bounded(v.qc,'QC observations');
    check(o,'QC identity uniqueness',new Set(qc.map(q=>q.sampleId+'|'+q.parameter+'|'+q.method)).size===qc.length,'Duplicate results require investigation.',source.id,'qc');
    for(const q of qc){const identified=text(q.sampleId)&&text(q.parameter)&&text(q.unit)&&text(q.method)&&q.batch===v.batch;
      const spec=finite(q.minimum)&&finite(q.maximum)&&q.minimum<=q.maximum&&text(q.specificationReference);
      check(o,(q.parameter||'QC')+' context',identified,'Batch, method, unit, sample and parameter must be explicit.',source.id,'qc');
      check(o,(q.parameter||'QC')+' specification',spec,'Both source-stated limits and their reference are required.',source.id,'qc');
      check(o,(q.parameter||'QC')+' result',finite(q.value)&&spec&&q.value>=q.minimum&&q.value<=q.maximum,finite(q.value)?`Observed ${q.value} ${q.unit||''}; stated limits ${q.minimum} to ${q.maximum}.`:'Critical value is absent. No replacement value is generated.',source.id,'qc');
    }
    o.metrics.qcObservations=qc.length;
    for(const r of s.records.filter(r=>['quality_events','investigation_records','capa_actions'].includes(r.kind)&&r.fields.batch===v.batch))check(o,'Open batch work '+r.id,['CLOSED','APPROVED'].includes(r.status)&&r.gaps.length===0,'Linked batch work is '+r.status+'.',r.id);
  }
  if(type==='batch-readiness'){
    const prerequisites=bounded(v.prerequisites,'Readiness prerequisites');
    check(o,'Prerequisite coverage',['QC_REVIEW','DEVIATION_REVIEW','TRAINING','DOCUMENT_REVIEW'].every(k=>prerequisites.some(p=>p.category===k)),'QC, deviations, training and documents must each have explicit evidence; absent work cannot imply readiness.',source.id,'prerequisites');
    check(o,'Unique prerequisites',new Set(prerequisites.map(p=>p.recordId)).size===prerequisites.length,'A single record cannot count repeatedly.',source.id,'prerequisites');
    for(const p of prerequisites){const r=s.records.find(x=>x.id===p.recordId);const d=s.records.find(x=>x.id===r?.fields.lastDecision&&x.kind==='human_decisions');const kinds:Record<string,string[]>={QC_REVIEW:['quality_events','assessments'],DEVIATION_REVIEW:['quality_events','investigation_records'],TRAINING:['training_impacts'],DOCUMENT_REVIEW:['controlled_sources','sop_mappings','requirements']};const categoryOK=!!r&&!!kinds[p.category]?.includes(r.kind)&&(r.kind!=='assessments'||r.fields.type==='batch-quality');check(o,'Readiness '+p.category,categoryOK&&!!r&&['APPROVED','CLOSED'].includes(r.status)&&!r.gaps.length&&!!d&&d.fields.recordVersion===r.version&&d.fields.action==='APPROVED',r?`${r.title}: ${r.status}; category-correct evidence and current named approval required.`:'Required evidence record is missing.',p.recordId,'prerequisites');}
    o.next.push('A named QA professional must decide batch disposition outside this readiness check. This report cannot release a batch.');
  }
  o.next.push('Resolve missing or conflicting source records, then rerun the check and obtain exact-revision human review.');
}

function oot(s:State,o:Output,source:Item){
  const v=decode(source,'LQ_TREND_V1');context(s,o,v,source);const history=bounded(v.history,'Prior comparable observations',1,100);const c=v.current||{};const rule=v.rule||{};o.metrics.batch=c.batch;
  const valid=finite(rule.lower)&&finite(rule.upper)&&rule.lower<rule.upper&&Number.isInteger(rule.minimumHistory)&&rule.minimumHistory>=6&&rule.minimumHistory<=100&&text(rule.reference)&&text(rule.rationale);
  check(o,'Documented review rule',valid,'A documented lower/upper rule, rationale and minimum of at least six prior observations are required.',source.id,'rule');
  check(o,'History size',valid&&history.length>=rule.minimumHistory,`${history.length} prior observations; required ${rule.minimumHistory??'not specified'}.`,source.id,'history');
  const identity=(x:any)=>text(x.batch)&&text(x.method)&&text(x.unit)&&text(x.parameter)&&finite(x.value)&&iso(x.date);
  check(o,'Current observation',identity(c),'Current value, batch, method, unit, parameter and date required.',source.id,'current');
  check(o,'Comparable prior observations',history.every(h=>identity(h)&&h.method===c.method&&h.unit===c.unit&&h.parameter===c.parameter&&h.date<c.date&&h.batch!==c.batch),'History must precede the current observation and use the same method, parameter and unit.',source.id,'history');
  check(o,'Independent history identities',new Set(history.map(h=>h.batch)).size===history.length,'Repeated measurements of the same batch cannot inflate this batch-trend denominator.',source.id,'history');
  if(!o.gaps.length){const alert=c.value<rule.lower||c.value>rule.upper;check(o,'OOT review',!alert,alert?`Current ${c.value} ${c.unit} is outside the documented review band ${rule.lower}–${rule.upper}.`:'Current result is within the documented review band.',source.id,'current.value');o.metrics.ootAlert=alert;o.metrics.historyCount=history.length;}
  o.next.push('Review trend context and the suitability of the supplied rule. An OOT alert is distinct from an OOS specification failure; neither establishes a root cause.');
}

export function officialURL(raw:unknown){try{const u=new URL(String(raw));return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&['fda.gov','ema.europa.eu','gov.uk','cdsco.gov.in','tga.gov.au','ich.org'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch{return false;}}
function regulatory(s:State,o:Output,source:Item){
  const v=decode(source,'LQ_REGULATORY_CHANGE_V1');const old=v.previous||{},current=v.current||{};
  for(const [label,x] of [['Previous',old],['Current',current]] as const){check(o,label+' official source',officialURL(x.url)&&text(x.sourceId)&&text(x.revision)&&iso(x.date)&&text(x.excerpt)&&/^[a-f0-9]{64}$/i.test(String(x.hash||'')),'Official HTTPS URL, ID, revision, date, exact excerpt and SHA-256 required. Imported metadata still needs source verification.',source.id,label.toLowerCase());const original=s.records.find(r=>r.id===x.localSourceId&&r.kind==='controlled_sources');check(o,label+' preserved original',!!original&&original.hash===x.hash&&String(original.fields.text||'').includes(x.excerpt),'Link a preserved local original with the same hash and exact excerpt; metadata alone is insufficient.',original?.id,label+'.localSourceId');}
  check(o,'Different revisions',old.revision!==current.revision&&old.hash!==current.hash,'Old/current revisions and hashes must differ.',source.id,'previous / current');
  check(o,'Source verification',v.sourceVerified===true&&text(v.verificationReference),'Imported discovery is not validated evidence. Record an authorized verification reference.',source.id,'verificationReference');
  const affected=bounded(v.affectedRecordIds,'Affected local records',0,50);
  for(const id of affected){const r=s.records.find(x=>x.id===id);check(o,'Affected record '+id,!!r&&['controlled_sources','requirements','sop_mappings','training_impacts','quality_events'].includes(r.kind),'A local requirement, SOP, training or quality record must exist before linkage.',id);}
  o.metrics.affectedRecordIds=affected;o.metrics.companyApplicability='UNKNOWN';o.next.push('Verify official originals, assess local applicability with a named reviewer, and request fresh review of affected SOP/training work. No company impact is inferred.');
}

function sop(s:State,o:Output,refs:Item[]){
  const mappings=refs.filter(r=>r.kind==='sop_mappings');check(o,'Mapping selection',mappings.length>0,'Select at least one SOP mapping.');
  for(const m of mappings){const req=s.records.find(r=>r.id===m.fields.requirementId&&r.kind==='requirements');const src=req&&s.records.find(r=>r.id===req.sourceIds[0]);const sop=s.records.find(r=>r.id===m.fields.sopId&&r.kind==='controlled_sources');check(o,'Requirement '+m.id,!!req&&!!src&&req.fields.sourceVersion===src.version&&String(src.fields.text||'').includes(req.fields.span)&&req.fields.statement===req.fields.span,'Requirement must have an exact current source excerpt.',req?.id);check(o,'SOP support '+m.id,!!sop&&text(m.fields.sopSpan)&&String(sop.fields.text||'').includes(m.fields.sopSpan)&&m.fields.coverage==='SUPPORTED'&&text(m.fields.rationale),'Supported coverage needs a current exact SOP excerpt and a human rationale.',sop?.id);}
  o.next.push('Resolve uncovered requirements; record reviewer judgement. Keyword similarity alone does not establish compliance.');
}
function risk(o:Output,refs:Item[]){for(const r of refs){const f=r.fields;const valid=[f.severity,f.likelihood,f.detectability].every(x=>Number.isInteger(Number(x))&&Number(x)>=1&&Number(x)<=5);check(o,r.title+' risk inputs',valid&&text(f.riskRationale),'Reviewer-supplied 1–5 severity, likelihood and detectability plus a rationale required.',r.id);if(valid&&text(f.riskRationale)){const score=Number(f.severity)*Number(f.likelihood)*Number(f.detectability);o.metrics[r.id]={score,scale:'Supplied 1–5 factors; review priority only'};}}o.next.push('Named QA accepts the scoring method and priorities; the score is not an inspection prediction or risk acceptance.');}
function investigation(o:Output,refs:Item[]){for(const r of refs){const f=r.fields;check(o,r.title+' first failure',text(f.firstFailure)&&Array.isArray(f.chronology)&&f.chronology.length>0,'Original first failure and chronology must be preserved.',r.id);check(o,r.title+' hypotheses',Array.isArray(f.hypotheses)&&f.hypotheses.length>0&&f.hypotheses.every((h:any)=>text(h.hypothesis)&&['unconfirmed','supported','rejected'].includes(h.state)&&text(h.evidenceId)),'Each hypothesis needs a state and evidence ID; unconfirmed hypotheses are not established cause.',r.id);check(o,r.title+' human conclusions',text(f.humanEstablishedCause)&&text(f.humanDisposition),'Root cause and disposition remain named human conclusions.',r.id);}o.next.push('Investigate the first failure; do not average, replace or discard it merely because a retest passes.');}
function effectiveness(s:State,o:Output,source:Item){const v=decode(source,'LQ_CAPA_EFFECTIVENESS_V1');const r=s.records.find(x=>x.id===v.capaId&&x.kind==='capa_actions');check(o,'CAPA identity',!!r,'Link an existing CAPA action.',v.capaId);for(const name of ['before','after']){const w=v[name]||{};check(o,name+' measurement window',iso(w.start)&&iso(w.end)&&w.start<=w.end&&Number.isInteger(w.events)&&w.events>=0&&Number.isInteger(w.exposure)&&w.exposure>0&&w.events<=w.exposure&&text(w.reference),'Dated measurement window, evidence reference, event count and nonzero exposure required.',source.id,name);}check(o,'Comparable windows',v.before?.end<v.after?.start&&text(v.measure)&&text(v.comparabilityRationale),'Before and after periods must not overlap; explain the measure and comparability.',source.id);check(o,'Effectiveness criterion',finite(v.maximumAfterRate)&&v.maximumAfterRate>=0&&v.maximumAfterRate<=1&&text(v.criterionReference),'Document a reviewed event-rate acceptance criterion.',source.id);if(!o.gaps.length){const before=v.before.events/v.before.exposure,after=v.after.events/v.after.exposure;o.metrics={beforeRate:before,afterRate:after,rateDifference:after-before,afterExposure:v.after.exposure};check(o,'Observed effectiveness criterion',after<=v.maximumAfterRate,`Observed after rate ${after}; criterion ${v.maximumAfterRate}. This does not itself establish causality.`,source.id);}o.next.push('Review implementation evidence, comparability and sufficient follow-up before human CAPA closure.');}
function apqr(s:State,o:Output,source:Item){const v=decode(source,'LQ_PERIOD_REVIEW_V1');context(s,o,v,source);check(o,'Defined period',iso(v.start)&&iso(v.end)&&v.start<=v.end,'A valid start/end period is required.',source.id);check(o,'Batch denominator',Number.isInteger(v.batchCount)&&v.batchCount>0&&text(v.denominatorReference),'Provide the total batch denominator with a source reference.',source.id);const events=s.records.filter(r=>r.kind==='quality_events'&&r.updated.slice(0,10)>=v.start&&r.updated.slice(0,10)<=v.end);o.metrics={savedEvents:events.length,batchCount:v.batchCount,byType:Object.fromEntries(uniq(events.map(e=>e.fields.eventType||'Unclassified')).map(k=>[k,events.filter(e=>e.fields.eventType===k).length]))};check(o,'Review coverage',Array.isArray(v.reviewedAreas)&&['batches','deviations','oos','changes','capa','training'].every(k=>v.reviewedAreas.includes(k))&&text(v.coverageReference),'All stated review areas need a source-backed completeness declaration.',source.id);o.next.push('Compare recorded counts with original period records. Small or incomplete samples cannot establish a process trend.');}
function models(s:State,o:Output){const runs=s.records.filter(r=>r.kind==='evaluation_runs'&&Array.isArray(r.fields.cases));const observed=runs.flatMap(r=>r.fields.cases.filter((c:any)=>c.mode==='Provider inference').map((c:any)=>({...c,runId:r.id})));check(o,'Actual model observations',observed.length>0,'No saved provider-inference evaluations exist. Deterministic fixtures do not count as model quality.');const latencies=observed.map(c=>c.latencyMs).filter(finite).sort((a,b)=>a-b);o.metrics.providerLatency=latencies.length?{observations:latencies.length,meanMs:latencies.reduce((a,b)=>a+b,0)/latencies.length,p95Ms:latencies[Math.max(0,Math.ceil(latencies.length*.95)-1)]}:null;o.metrics.billingCost='Not recorded; provider billing is required for a cost claim.';const groups=uniq(observed.map(c=>String(c.family||'Unclassified')));o.metrics.groups=groups.map(g=>{const rows=observed.filter(c=>c.family===g);return {group:g,observations:rows.length,passed:rows.filter(c=>c.pass===true).length,criticalFailures:rows.filter(c=>c.critical&&!c.pass).length};});check(o,'Group comparison coverage',groups.length>=2,'At least two reviewer-defined groups are needed for a limited comparison; representativeness remains unproven.');for(const c of observed)if(c.critical&&!c.pass)check(o,'Critical model failure '+c.runId,false,'A recorded critical failure must remain visible.',c.runId);o.next.push('Use held-out, reviewer-approved cases. This summary neither certifies fairness nor qualifies an intended use.');}
function privacy(o:Output,source:Item){const v=decode(source,'LQ_DATA_POLICY_V1');for(const k of ['purpose','owner','permittedData','providerPermission','retentionBasis','deletionProcedure','legalHoldProcedure','incidentContact'])check(o,k,text(v[k]),'Document the owner-approved '+k+'; no automatic legal basis is assumed.',source.id,k);check(o,'Retention dates',iso(v.reviewDate)&&Number.isInteger(v.retentionDays)&&v.retentionDays>=30&&v.retentionDays<=3650,'A documented review date and bounded retention period are required.',source.id);o.next.push('Owner handles authorized deletion requests after legal-hold review. This workflow records requests; it does not silently delete regulated evidence.');}
function requirements(s:State,o:Output,source:Item){const v=decode(source,'LQ_AI_REQUIREMENTS_V1');for(const row of bounded(v.requirements,'AI requirements')){const evidence=s.records.find(r=>r.id===row.evidenceId);check(o,row.name||'Requirement',text(row.name)&&officialURL(row.authorityURL)&&text(row.applicabilityRationale)&&text(row.controlId)&&!!evidence&&text(row.reviewer),'Record official authority, applicability, local control/evidence and named review. Applicability is human judgement.',row.evidenceId,'requirements');}o.next.push('A qualified reviewer confirms which requirements apply; this mapping is not a legal compliance certificate.');}
function improvement(s:State,o:Output,source:Item){const v=decode(source,'LQ_IMPROVEMENT_V1');for(const row of bounded(v.actions,'Improvement actions')){const target=s.records.find(r=>r.id===row.recordId);check(o,row.title||'Action',!!target&&text(row.owner)&&iso(row.due)&&text(row.measure)&&text(row.successCriterion)&&text(row.measurementReference),'Action needs a linked quality record, owner, deadline and source-backed success measure.',row.recordId);}o.next.push('Review overdue work and compare actual follow-up against the agreed measure. No predicted benefit is generated.');}

export function assess(s:State,type:AssessmentType,ids:string[]):Item {
  if(!Object.hasOwn(assessmentTypes,type)||!Array.isArray(ids)||!ids.length||ids.length>20||new Set(ids).size!==ids.length)throw new Error('Select a supported check and 1–20 distinct evidence records.');
  const refs=ids.map(id=>{const r=s.records.find(r=>r.id===id);if(!r)throw new Error('Evidence is not in this workspace.');return r;});
  const o:Output={checks:[],gaps:[],metrics:{},next:[],summary:''};
  // Capture the complete upstream closure; changes invalidate this record through sourceIds.
  const seen=new Set<string>();function visit(r:Item){if(seen.has(r.id))return;seen.add(r.id);for(const id of r.sourceIds){const child=s.records.find(x=>x.id===id);if(child)visit(child);else check(o,'Missing dependency '+id,false,'Linked evidence is unavailable.');}if(r.gaps.length||badStates.includes(r.status))check(o,'Current evidence '+r.id,false,'Evidence is '+r.status+' with '+r.gaps.length+' unresolved gap(s).',r.id);}
  refs.forEach(visit);const sources=refs.filter(r=>r.kind==='controlled_sources');
  if(['batch-record','batch-quality','batch-readiness','oot','regulatory','effectiveness','apqr','privacy','requirements','improvement'].includes(type)&&sources.length!==1)throw new Error('Choose exactly one current structured source for this check.');
  if(type.startsWith('batch-'))batch(s,o,sources[0],type);
  else if(type==='oot')oot(s,o,sources[0]);else if(type==='regulatory')regulatory(s,o,sources[0]);
  else if(type==='sop')sop(s,o,refs);else if(type==='risk')risk(o,refs);else if(type==='investigation')investigation(o,refs);
  else if(type==='effectiveness')effectiveness(s,o,sources[0]);else if(type==='apqr')apqr(s,o,sources[0]);
  else if(type==='model'){const before=new Set(seen);for(const r of s.records.filter(r=>r.kind==='evaluation_runs'))visit(r);models(s,o);o.metrics.scope='Saved observations only; '+(seen.size-before.size)+' linked evaluation records.';}
  else if(type==='privacy')privacy(o,sources[0]);else if(type==='requirements')requirements(s,o,sources[0]);else if(type==='improvement')improvement(s,o,sources[0]);
  else {for(const r of refs){check(o,r.id+' title',text(r.title),'Title required.',r.id);if(r.kind==='requirements'){const src=s.records.find(x=>x.id===r.sourceIds[0]);check(o,r.id+' exact grounding',!!src&&r.fields.sourceVersion===src.version&&r.fields.statement===r.fields.span&&text(r.fields.span)&&String(src.fields.text||'').includes(r.fields.span),'Current exact source support required.',r.id);}if(r.kind==='controlled_sources')check(o,r.id+' provenance',!!r.hash&&!!r.fields.objectKey&&r.fields.permission===true,'Saved original/hash and permission must be recorded.',r.id);}o.next.push('Resolve duplicate/conflicting records against the original; no automatic record merging.');}
  // Secondary batch prerequisites, model runs and quality events are dependencies too.
  for(const c of o.checks){const linked=s.records.find(r=>r.id===c.sourceId);if(linked)visit(linked);}
  if(type==='apqr')for(const r of s.records.filter(r=>r.kind==='quality_events'))visit(r);
  o.gaps=uniq(o.gaps);o.summary=o.gaps.length?`${assessmentTypes[type]} found ${o.gaps.length} unresolved item(s). Keep this work on HOLD and resolve the listed evidence.`:`${assessmentTypes[type]} completed its ${o.checks.length} bounded checks. Named human review is still required; no release is granted.`;
  const r=newItem('assessments',assessmentTypes[type],{type,ruleVersion:'extra-features-v1',...o,scope:'Source-linked portfolio quality support. Not batch release, regulatory advice, independent validation or established commercial outcomes.',inputVersions:[...seen].map(id=>{const x=s.records.find(r=>r.id===id)!;return {id,version:x.version,hash:x.hash||null};})},[...seen],o.gaps.length?'HOLD':'REVIEW REQUIRED');r.gaps=o.gaps;return r;
}
export function assertAssessmentCurrent(s:State,r:Item){if(r.kind!=='assessments')return;for(const v of r.fields.inputVersions||[]){const src=s.records.find(x=>x.id===v.id);if(!src||src.version!==v.version||(v.hash&&src.hash!==v.hash))throw new Error('Assessment input changed. Rerun against current evidence.');}if(!Array.isArray(r.fields.checks)||!r.fields.checks.length||r.fields.checks.some((c:any)=>c.pass!==true))throw new Error('Unresolved assessment checks block approval.');}
export function evidenceClosure(s:State,target:Item){const seen=new Set<string>();function visit(r:Item){if(seen.has(r.id))return;seen.add(r.id);for(const id of r.sourceIds){const child=s.records.find(x=>x.id===id);if(!child)throw new Error('Export cannot omit missing evidence '+id);visit(child);}if(r.fields.lastDecision){const d=s.records.find(x=>x.id===r.fields.lastDecision);if(d)visit(d);}}visit(target);return s.records.filter(r=>seen.has(r.id));}
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHTML(packet:any){const target=packet.records.find((r:Item)=>r.id===packet.targetId) as Item;const checks=target?.fields.checks||[];return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>LEDGER-Q evidence report</title><style>body{font:15px/1.6 system-ui;color:#213342;max-width:1050px;margin:40px auto;padding:0 24px}h1{font-size:26px}h2{font-size:19px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;border:1px solid #b9cbd3;padding:10px;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eef5f7;padding:12px}.boundary{background:#edf5f8;border-left:4px solid #28758d;padding:16px}@media print{body{margin:0}button{display:none}tr{break-inside:avoid}}</style><h1>${escape(target?.title)}</h1><p class="boundary">${escape(packet.limitations)}<br>State: ${escape(target?.status)} · Workspace revision ${escape(packet.revision)} · Record v${escape(target?.version)}</p><p>${escape(target?.fields.summary||'Review the saved source records and decision history below.')}</p><h2>Findings</h2><table><thead><tr><th>Check</th><th>Finding</th><th>Result</th><th>Evidence</th></tr></thead><tbody>${checks.map((c:Check)=>`<tr><td>${escape(c.item)}</td><td>${escape(c.finding)}</td><td>${c.pass?'CHECK MET':'GAP / HOLD'}</td><td>${escape(c.sourceId)} ${escape(c.path)}</td></tr>`).join('')}</tbody></table><h2>Missing evidence / next action</h2><ul>${[...(target?.gaps||[]),...(target?.fields.next||[])].map(x=>`<li>${escape(x)}</li>`).join('')}</ul><h2>Exact saved evidence and decisions</h2>${packet.records.map((r:Item)=>`<section><h3>${escape(r.id)} · ${escape(r.title)} · v${escape(r.version)} · ${escape(r.status)}</h3><p>Hash: ${escape(r.hash||'record metadata in JSON packet')}</p><pre>${escape(JSON.stringify(r.fields,null,2))}</pre></section>`).join('')}<p>Report snapshot: ${escape(packet.created)}. Changed evidence needs fresh review. JSON packet preserves the structured history.</p><button onclick="window.print()">Print / Save as PDF</button></html>`;}

export const sourceTemplates:Record<string,any>={
 batch:{format:'LQ_BATCH_V1',productId:'PRODUCT-LQ-001',siteId:'SITE-LQ-DEMO',batch:'LQ-026',requiredSteps:['Line clearance','Reconciliation'],steps:[{step:'Line clearance',expected:'Completed',observed:'Completed',reference:'SYNTHETIC-BMR-026 page 1',performedBy:'Synthetic operator',date:'2026-10-01'},{step:'Reconciliation',expected:'Completed',observed:null,reference:'SYNTHETIC-BMR-026 page 2',performedBy:'',date:'2026-10-01'}],qc:[{sampleId:'LQ-026-01',batch:'LQ-026',parameter:'Assay',value:94.2,unit:'%',method:'HPLC-Q02',minimum:95,maximum:105,specificationReference:'Synthetic specification v1'}],prerequisites:[{category:'QC_REVIEW',recordId:'EVT-OOS-026'},{category:'DEVIATION_REVIEW',recordId:'INV-026'},{category:'TRAINING',recordId:'Replace with current training record'},{category:'DOCUMENT_REVIEW',recordId:'Replace with current document review'}]},
 oot:{format:'LQ_TREND_V1',productId:'PRODUCT-LQ-001',siteId:'SITE-LQ-DEMO',rule:{lower:97,upper:103,minimumHistory:6,reference:'Synthetic QC trend rule v1',rationale:'Fixed demonstration review band; requires professional suitability review.'},history:Array.from({length:6},(_,i)=>({batch:'LQ-02'+i,date:'2026-09-'+String(10+i).padStart(2,'0'),value:99+i*.1,unit:'%',method:'HPLC-Q02',parameter:'Assay'})),current:{batch:'LQ-026',date:'2026-10-01',value:104,unit:'%',method:'HPLC-Q02',parameter:'Assay'}},
 regulatory:{format:'LQ_REGULATORY_CHANGE_V1',origin:'BEACON export / authorized manual intake',previous:{sourceId:'ICH-Q9',revision:'2005',date:'2005-11-09',url:'https://www.ich.org/page/quality-guidelines',hash:'Replace with verified original SHA-256',excerpt:'Insert exact verified old excerpt'},current:{sourceId:'ICH-Q9-R1',revision:'2023',date:'2023-01-18',url:'https://www.ich.org/page/quality-guidelines',hash:'Replace with verified original SHA-256',excerpt:'Insert exact verified current excerpt'},sourceVerified:false,verificationReference:'',affectedRecordIds:['SRC-SOP-014']},
 effectiveness:{format:'LQ_CAPA_EFFECTIVENESS_V1',capaId:'CAPA-026',measure:'Repeated documentation omission',comparabilityRationale:'Synthetic comparable batch review periods',before:{start:'2026-08-01',end:'2026-08-31',events:4,exposure:20,reference:'Synthetic August review'},after:{start:'2026-09-01',end:'2026-09-30',events:1,exposure:20,reference:'Synthetic September review'},maximumAfterRate:.05,criterionReference:'Synthetic reviewer-proposed criterion; professional approval required'},
 apqr:{format:'LQ_PERIOD_REVIEW_V1',productId:'PRODUCT-LQ-001',siteId:'SITE-LQ-DEMO',start:'2026-01-01',end:'2026-12-31',batchCount:20,denominatorReference:'Synthetic annual batch register',reviewedAreas:['batches','deviations','oos','changes','capa','training'],coverageReference:'Synthetic completeness declaration; verify against originals'},
 privacy:{format:'LQ_DATA_POLICY_V1',purpose:'Independent synthetic portfolio exercise',owner:'Workspace owner',permittedData:'Synthetic / permission-granted public evidence',providerPermission:'Explicit per-workspace opt-in before external processing',retentionBasis:'Owner-approved exercise period; not a legal determination',retentionDays:365,reviewDate:'2027-01-01',deletionProcedure:'Owner logs request and checks legal holds before authorized handling',legalHoldProcedure:'Preserve evidence when required; named owner review',incidentContact:'Insert operational support contact'},
 requirements:{format:'LQ_AI_REQUIREMENTS_V1',requirements:[{name:'Data integrity review',authorityURL:'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/data-integrity-and-compliance-drug-cgmp-questions-and-answers-guidance-industry',applicabilityRationale:'To be confirmed for the intended use',controlId:'Original preservation',evidenceId:'SRC-SOP-014',reviewer:'Named qualified reviewer required'}]},
 improvement:{format:'LQ_IMPROVEMENT_V1',actions:[{recordId:'CAPA-026',title:'Preserve original investigation evidence',owner:'Demo process owner',due:'2026-10-20',measure:'Missing first-failure records',successCriterion:'No missing original record in the reviewed sample',measurementReference:'Synthetic follow-up checklist'}]},
};
export function addExtensionProof(s:State){if(s.records.some(r=>r.id==='EXTRA-BATCH-SOURCE'))throw new Error('Additional synthetic proof already exists.');const made:Item[]=[];for(const [key,value] of Object.entries(sourceTemplates)){const r=newItem('controlled_sources','Synthetic '+key+' evidence',{text:JSON.stringify(value,null,2),purpose:'Independent additional-features proof',permission:true,filename:key+'-synthetic.json',contentType:'text/plain'},[],'CURRENT');r.id=key==='batch'?'EXTRA-BATCH-SOURCE':'EXTRA-'+key.toUpperCase()+'-SOURCE';made.push(r);}s.records.push(...made);for(const [type,key] of [['batch-record','batch'],['batch-quality','batch'],['batch-readiness','batch'],['oot','oot'],['regulatory','regulatory'],['effectiveness','effectiveness'],['apqr','apqr']] as const)s.records.push(assess(s,type,[made.find(r=>r.id===(key==='batch'?'EXTRA-BATCH-SOURCE':'EXTRA-'+key.toUpperCase()+'-SOURCE'))!.id]));return made;}
