import {type State,now,uid,newItem} from './types';
import {hash} from './security';
export type Runtime={DB:any;BUCKET:any;LQ_ENCRYPTION_KEY:string;GROQ_API_KEY?:string;GEMINI_API_KEY?:string};
export function db(env:Runtime){if(!env.DB)throw new Error('Saved storage is unavailable. Please try again.');return env.DB;}
export async function one(env:Runtime,sql:string,...args:any[]){return db(env).prepare(sql).bind(...args).first();}
export async function all(env:Runtime,sql:string,...args:any[]){return (await db(env).prepare(sql).bind(...args).all()).results||[];}
export async function sql(env:Runtime,query:string,...args:any[]){return db(env).prepare(query).bind(...args).run();}
export async function load(env:Runtime,id:string,userId:string){const row=await one(env,'SELECT w.*, m.roles FROM workspaces w JOIN members m ON m.workspace_id=w.id WHERE w.id=? AND m.user_id=?',id,userId);if(!row)throw new Error('Workspace access denied.');return {...row,state:JSON.parse(row.state) as State,roles:JSON.parse(row.roles) as string[]};}
export function permission(row:any,allowed:string[]){if(!row.roles.some((r:string)=>allowed.includes(r)))throw new Error('Your current role cannot perform this action.');}
export async function commit(env:Runtime,row:any,state:State,actor:string,action:string,key:string,effects:{query:string;args:any[]}[]=[],output:Record<string,any>={}){const seen=await one(env,'SELECT result FROM operations WHERE workspace_id=? AND key=?',row.id,key);if(seen)return {replayed:true,...JSON.parse(seen.result)};const opId=uid('OP');const next=row.revision+1;const at=now();const prev=await one(env,'SELECT hash FROM audit_events WHERE workspace_id=? ORDER BY revision DESC LIMIT 1',row.id);const previousHash=prev?.hash||'GENESIS';const digest=await hash(JSON.stringify({workspace:row.id,revision:next,actor,action,previousHash,state}));const event=newItem('audit_events',action,{actor,revision:next,previousHash,hash:digest,operationId:opId},[],'RECORDED');event.updated=at;state.records.push(event);if(state.records.length>1500)throw new Error('Workspace record limit reached; export and contact the owner.');const serialized=JSON.stringify(state);if(serialized.length>1800000)throw new Error('Workspace size limit reached.');const result={...output,revision:next,operationId:opId};const batch=await db(env).batch([
 db(env).prepare('UPDATE workspaces SET state=?,revision=?,last_operation=?,updated=? WHERE id=? AND revision=?').bind(serialized,next,opId,at,row.id,row.revision),
 db(env).prepare('INSERT INTO workspace_versions(id,workspace_id,revision,state,hash,created) SELECT ?,id,revision,state,?,? FROM workspaces WHERE id=? AND last_operation=?').bind(uid('VER'),await hash(serialized),at,row.id,opId),
 db(env).prepare('INSERT INTO audit_events(id,workspace_id,revision,actor,action,previous_hash,hash,created) SELECT ?,id,revision,?,?,?,?,? FROM workspaces WHERE id=? AND last_operation=?').bind(event.id,actor,action,previousHash,digest,at,row.id,opId),
 db(env).prepare('INSERT INTO operations(id,workspace_id,key,result,created) SELECT ?,id,?,?,? FROM workspaces WHERE id=? AND last_operation=?').bind(opId,key,JSON.stringify(result),at,row.id,opId),
 ...effects.map(effect=>db(env).prepare(effect.query).bind(...effect.args,row.id,opId))
 ]);if(batch[0].meta.changes!==1)throw new Error('This workspace changed. Refresh and review the current revision before saving.');return result;}
