'use client';
import {useEffect,useState} from 'react';
import type {ProofStep} from '@/lib/ledger/proof';
type Report={revision:number;checkedAt:string;scope:string;steps:ProofStep[]};
export default function TenStepProof({compact=false}:{compact?:boolean}){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch('/api/ledger/proof-checklist',{signal:abort.signal,cache:'no-store'}).then(async r=>{const data=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(data.error||'Saved proof is unavailable.');if(!Array.isArray(data.steps)||data.steps.length!==10)throw new Error("Invalid saved proof response.");setReport(data);}).catch(e=>{if(e.name!=='AbortError')setError('Saved proof could not be read. This is an evidence gap; no successful result is assumed.');});return()=>abort.abort();},[]);
 return <section className={'ten-step-proof '+(compact?'compact-proof':'full-proof')} aria-labelledby="ten-step-title" id="ten-step-proof"><div className="proof-section-heading"><div><p className="overline">SAVED SYNTHETIC WORK SAMPLE</p><h2 id="ten-step-title">Ten steps. Evidence you can inspect.</h2><p>Follow the original record, the unresolved conflict and the human decision boundary. These checks read the saved public proof; they do not load it into your private workspace.</p></div><a className="proof-link" href={compact?'/mvp-checklist':'/app?demo=1'}>{compact?'Inspect all ten steps':'Open saved working proof'} <span aria-hidden="true">↗</span></a></div>{error?<p role="alert" className="proof-gap">{error}</p>:!report?<p role="status">Reading saved proof…</p>:<><p className="proof-revision">Public proof revision {report.revision} · checked {new Date(report.checkedAt).toLocaleString('en-GB')} · synthetic portfolio exercise</p><div className="proof-step-grid">{report.steps.map(step=><a key={step.id} href={step.href} className={'proof-step proof-status-'+step.status.toLowerCase().replaceAll(' ','-')}><div className="proof-step-top"><span className="proof-step-number">{step.id}</span><span className="proof-step-status">{step.status==='DEMONSTRATED'?'Control demonstrated':step.status==='PARTIAL'?'Partial / review needed':'Not established'}</span></div><h3>{step.title}</h3><p>{step.observation}</p><span className="proof-step-open">Inspect evidence <span aria-hidden="true">↗</span></span></a>)}</div><p className="proof-boundary">{report.scope}</p><div className="proof-resource-links"><a href="/api/ledger/proof-checklist">Read the saved-proof check results (JSON)</a><a href="/work-samples/LEDGER_Q_Ten_Step_Checklist.pdf">Open the full checklist PDF</a></div></>}</section>;
}
