import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
mkdirSync('.test-build',{recursive:true});
for(const name of ['types','quality-controls','engine','extensions'])writeFileSync('.test-build/'+name+'.js',ts.transpileModule(readFileSync('lib/ledger/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.js'"));
const {assess,sourceTemplates,assertAssessmentCurrent,reportHTML,evidenceClosure,officialURL,addExtensionProof}=await import('../.test-build/extensions.js');
const {scenario,emptyWorkspace,invalidate}=await import('../.test-build/engine.js');
const {newItem}=await import('../.test-build/types.js');
const results=[];
function test(name,fn){fn();results.push({name,result:'PASS'});console.log('PASS '+name);}
function fixture(template){const s=scenario('fixture',false),v=structuredClone(sourceTemplates[template]);const r=newItem('controlled_sources','Synthetic input',{text:JSON.stringify(v),objectKey:'fixture/input.txt',permission:true},[],'CURRENT');r.hash='fixture-hash';s.records.push(r);return {s,v,r,run:type=>{r.fields.text=JSON.stringify(v);return assess(s,type,[r.id]);}};}
test('New workspace has no proof, assessments or provider consent',()=>{const s=emptyWorkspace('fresh');assert.equal(s.records.length,0);assert.equal(s.policy.providerConsent,false);});
test('Critical missing batch record cannot pass',()=>{const {run}=fixture('batch');const r=run('batch-record');assert.equal(r.status,'HOLD');assert(r.gaps.some(g=>g.includes('Reconciliation')));});
test('Complete records become review-required, never released',()=>{const {v,run}=fixture('batch');v.steps[1].observed='Completed';v.steps[1].performedBy='Synthetic operator';const r=run('batch-record');assert.equal(r.status,'REVIEW REQUIRED');assert.equal(r.fields.metrics.requiredSteps,2);assert.notEqual(r.status,'APPROVED');});
test('Empty manifest cannot imply complete batch',()=>{const {v,run}=fixture('batch');v.requiredSteps=[];assert.throws(()=>run('batch-record'),/Required batch steps/);});
test('Duplicate steps cannot inflate completeness',()=>{const {v,run}=fixture('batch');v.steps.push(v.steps[0]);assert.equal(run('batch-record').status,'HOLD');});
test('Wrong product/site stays HOLD',()=>{const {v,run}=fixture('batch');v.productId='Another product';assert(run('batch-record').gaps.some(g=>g.includes('Product and site')));});
test('Out-of-spec result remains original and held',()=>{const {v,run}=fixture('batch');const r=run('batch-quality');assert.equal(v.qc[0].value,94.2);assert(r.gaps.some(g=>g.includes('94.2')));});
test('Missing assay cannot be replaced by a passing retest',()=>{const {v,run}=fixture('batch');v.qc[0].value=null;assert(run('batch-quality').gaps.some(g=>g.includes('Critical value is absent')));});
test('Missing method/unit blocks quality progression',()=>{const {v,run}=fixture('batch');v.qc[0].method='';v.qc[0].unit='';assert(run('batch-quality').gaps.some(g=>g.includes('context')));});
test('Batch readiness requires four explicit review categories',()=>{const {v,run}=fixture('batch');v.prerequisites=[{category:'QC_REVIEW',recordId:'EVT-OOS-026'}];assert(run('batch-readiness').gaps.some(g=>g.includes('Prerequisite coverage')));});
test('Present but unsigned prerequisites cannot establish readiness',()=>{const {run}=fixture('batch');assert(run('batch-readiness').gaps.some(g=>g.includes('current named approval')));});
test('OOT band alert is separate from specification failure',()=>{const {run}=fixture('oot');const r=run('oot');assert.equal(r.status,'HOLD');assert.equal(r.fields.metrics.ootAlert,true);assert.equal(r.fields.metrics.historyCount,6);});
test('OOT inside documented band still requires human review',()=>{const {v,run}=fixture('oot');v.current.value=100;assert.equal(run('oot').status,'REVIEW REQUIRED');});
test('Insufficient history does not imply no OOT',()=>{const {v,run}=fixture('oot');v.history=v.history.slice(0,3);const r=run('oot');assert.equal(r.status,'HOLD');assert.equal(r.fields.metrics.ootAlert,undefined);});
test('Incomparable units block OOT calculation',()=>{const {v,run}=fixture('oot');v.history[0].unit='mg';const r=run('oot');assert(r.gaps.some(g=>g.includes('Comparable prior')));assert.equal(r.fields.metrics.ootAlert,undefined);});
test('Future observations cannot become prior history',()=>{const {v,run}=fixture('oot');v.history[0].date='2027-01-01';assert.equal(run('oot').status,'HOLD');});
test('Duplicate prior identities cannot inflate trend denominator',()=>{const {v,run}=fixture('oot');v.history[1]=v.history[0];assert.equal(run('oot').status,'HOLD');});
test('Undocumented trend rule remains a gap',()=>{const {v,run}=fixture('oot');v.rule.reference='';assert.equal(run('oot').status,'HOLD');});
test('Calendar-overflow dates fail validation',()=>{const {v,run}=fixture('oot');v.current.date='2026-02-31';assert.equal(run('oot').status,'HOLD');});
test('Official allowlist rejects suffix spoofing and URL credentials',()=>{assert(officialURL('https://www.fda.gov/a'));for(const u of ['http://www.fda.gov/a','https://fda.gov.evil.test/a','https://evil.test/?u=fda.gov','https://u:p@www.fda.gov/a','https://www.fda.gov:444/a'])assert(!officialURL(u));});
test('Regulatory discovery without verification stays HOLD',()=>{const {run}=fixture('regulatory');const r=run('regulatory');assert.equal(r.status,'HOLD');assert.equal(r.fields.metrics.companyApplicability,'UNKNOWN');});
test('Same old/current version cannot become change evidence',()=>{const {v,run}=fixture('regulatory');v.current=v.previous;assert(run('regulatory').gaps.some(g=>g.includes('Different revisions')));});
test('Foreign affected record does not create a local mapping',()=>{const {v,run}=fixture('regulatory');v.affectedRecordIds=['FOREIGN'];assert(run('regulatory').gaps.some(g=>g.includes('FOREIGN')));});
test('Changed source invalidates assessment and blocks old approval',()=>{const {s,r,v,run}=fixture('oot');v.current.value=100;const result=run('oot');s.records.push(result);r.version++;invalidate(s,r.id);assert.equal(result.status,'STALE');assert.throws(()=>assertAssessmentCurrent(s,result),/changed/);});
test('Failed computed checks cannot receive approval',()=>{const {s,run}=fixture('batch');assert.throws(()=>assertAssessmentCurrent(s,run('batch-readiness')),/Unresolved/);});
test('CAPA rate comparison preserves exposure and does not establish causality',()=>{const {run}=fixture('effectiveness');const r=run('effectiveness');assert.equal(r.fields.metrics.afterRate,.05);assert.equal(r.fields.metrics.afterExposure,20);assert(r.fields.next.some(n=>n.includes('human CAPA closure')));});
test('Zero exposure cannot produce effectiveness success',()=>{const {v,run}=fixture('effectiveness');v.after.exposure=0;assert.equal(run('effectiveness').status,'HOLD');});
test('Overlapping CAPA windows block comparison',()=>{const {v,run}=fixture('effectiveness');v.after.start=v.before.start;assert.equal(run('effectiveness').status,'HOLD');});
test('Missing APQR denominator is an explicit gap',()=>{const {v,run}=fixture('apqr');v.batchCount=0;assert.equal(run('apqr').status,'HOLD');});
test('Deterministic fixtures cannot be counted as actual model quality',()=>{const s=scenario('model');const r=assess(s,'model',['AI-QA-01']);assert.equal(r.status,'HOLD');assert(r.gaps.some(g=>g.includes('Actual model observations')));});
test('Unscored risk is UNKNOWN rather than invented high confidence',()=>{const s=scenario('risk');const r=assess(s,'risk',['EVT-OOS-026']);assert.equal(r.status,'HOLD');assert.equal(r.fields.metrics['EVT-OOS-026'],undefined);});
test('SOP keyword match without exact excerpt cannot establish coverage',()=>{const s=scenario('sop');const m=s.records.find(r=>r.kind==='sop_mappings');m.fields.coverage='SUPPORTED';const r=assess(s,'sop',[m.id]);assert.equal(r.status,'HOLD');});
test('HTML exports escape source injection and preserve HOLD',()=>{const {run}=fixture('batch');const r=run('batch-record');r.title='<script>unsafe()</script>';const html=reportHTML({targetId:r.id,records:[r],limitations:'UNAPPROVED',revision:3,created:'fixture'});assert(!html.includes('<script>unsafe'));assert(html.includes('&lt;script&gt;'));assert(html.includes('HOLD'));});
test('Export follows transitive evidence, decisions and immutable history',()=>{const s=scenario('closure');const capa=s.records.find(r=>r.id==='CAPA-026');const closure=evidenceClosure(s,capa);assert(closure.some(r=>r.id==='SRC-LAB-026'));assert(closure.some(r=>r.id==='EVT-OOS-026'));});
test('Export cannot omit missing evidence',()=>{const s=scenario('missing');s.records.find(r=>r.id==='CAPA-026').sourceIds.push('missing');assert.throws(()=>evidenceClosure(s,s.records.find(r=>r.id==='CAPA-026')),/cannot omit/);});
test('Additional proof is explicit and preserves original held investigation',()=>{const s=scenario('extra');addExtensionProof(s);assert.equal(s.records.filter(r=>r.kind==='assessments').length,7);assert.equal(s.records.find(r=>r.id==='EVT-OOS-026').status,'HOLD');assert.throws(()=>addExtensionProof(s),/already/);});
test('Invalid or duplicate selected input cannot silently count twice',()=>{const {s,r}=fixture('batch');assert.throws(()=>assess(s,'batch-record',[r.id,r.id]),/distinct/);assert.throws(()=>assess(s,'unknown',[r.id]),/supported/);});
mkdirSync('docs/verification',{recursive:true});writeFileSync('docs/verification/extra-feature-checks.json',JSON.stringify({at:new Date().toISOString(),scope:'Executed synthetic unit/adverse checks. No independent professional or production validation.',passed:results.length,results},null,2));
